### ISSUE TITLE
Или баг или я дурак )

### ISSUE THREAD

**Issue by llimonix** [FozerG/WinYandexMusicRPC#1]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/58168234/1c291b6a-a74f-4a59-a421-0b51a16d30d9)

**Comment by llimonix** [comment]
Запущен discord ptb (бета версия, так как основный дс не работает). Я так понимаю вам нужно добавить в скрипт нахождение дискорд птб и канари

**Comment by llimonix** [comment]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/58168234/0c727f54-dbf6-4df5-ac39-87c1c0a07c49)
exe ptb версии. Увы канари посмотреть не могу

**Comment by llimonix** [comment]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/58168234/b3526160-c50b-4e7c-a10e-34f4a1182840)

допишите () скобки после exit и баг из первого сообщения не повторится

**Comment by llimonix** [comment]
Добавьте задержку перед проверкой, когда музыка играла и закончилась, и идет загрузка след трека. Чтобы активность не пропадала на несколько секунд.

**Comment by FozerG** [comment]
Должно быть исправлено, спасибо. По поводу задержки - нет возможности определить, что трек действительно завершился, так как приложения по-разному передают состояние аудио, и чаще всего для конца трека и паузы используется одно состояние.
