### ISSUE TITLE
Не работает кнопка прослушивания

### ISSUE THREAD

**Issue by MasterKote** [FozerG/WinYandexMusicRPC#10]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/163345130/dfd0b9d2-9af9-4bfb-93bb-ad3ba810cb7a)

**Comment by FozerG** [comment]
Я потратил 2 часа на попытку выявления проблемы. Как я понял, проблема на стороне десктопной и веб-версии Discord. В мобильной версии всё работает. На стороне скрипта все нормально, перестали работать даже старые версии, которые точно работали. Будем ждать фикса или новостей. 😢

**Comment by KOTOKOPOLb** [comment]
Проблемы на стороне Discord.
Проверил на своих кодах - кнопки не работают. В мобильной версии они вообще не отображаются.

**Comment by KOTOKOPOLb** [comment]
Кнопки снова работают
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/82699565/f20b9250-d699-432d-a7df-84325f5343e3)
