### ISSUE TITLE
Время останавливается на 0:00, когда трек играет на повторе

### ISSUE THREAD

**Issue by MrEnderLit1** [FozerG/WinYandexMusicRPC#15]
![изображение](https://github.com/FozerG/WinYandexMusicRPC/assets/158048397/6b903ead-70e4-48d5-aebb-28948466ea59)

**Comment by FozerG** [comment]
Какой браузер/приложение яндекс музыки используешь (новое/старое)? Слушаешь через Яндекс музыку? Используешь последнию версию скрипта?

**Comment by MrEnderLit1** [comment]
> Какой браузер/приложение яндекс музыки используешь (новое/старое)? Слушаешь через Яндекс музыку? Используешь последнию версию скрипта?

Использовал Firefox, с новым приложением яндекса такой проблемы нет. Слушаю через яндекс музыку с последней версии скрипта

**Comment by FozerG** [comment]
> > Какой браузер/приложение яндекс музыки используешь (новое/старое)? Слушаешь через Яндекс музыку? Используешь последнию версию скрипта?
> 
> Использовал Firefox, с новым приложением яндекса такой проблемы нет. Слушаю через яндекс музыку с последней версии скрипта

Значит Firefox не передает медиаданные со временем в windows api. Да и в целом, время поддерживается только в новом приложении и Google Chrome.
