### ISSUE TITLE
Не работает, если сидишь через VPN

### ISSUE THREAD

**Issue by TuTAH1** [FozerG/WinYandexMusicRPC#16]
Прога распознаёт полное название песни, но не всовывает его в RPC. Полагаю, что из-за этой.. ошибки?

![image](https://github.com/FozerG/WinYandexMusicRPC/assets/15982179/bf858348-d9c8-4643-a9f7-a856726ccceb)

Но он всё же вытащил полное название песни, может в таком случае игнорить ошибку и вставлять в DRP то, что есть?

Проблема появляется только при включённом VPN

**Comment by FozerG** [comment]
То что определило трек это заслуга winsdk, но проблема в том что в winsdk могут быть так же видоролики с ютуба, а отличить музыку от видео без поиска на яндекс музыке нельзя, и было бы неожиданным выводить видео с ютуба в RPC 🤨

А по поводу ошибки - могу предложить не использовать впн или редактировать main.py для того что бы запросы были с личным токеном яндекс музыки. Я необходимость поддержки такой функции сейчас не вижу.
