### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by UrbanSide** [FozerG/WinYandexMusicRPC#18]
Ребят а у вас нигде не булькнуло логотипу ноги приделать чужому?)
@eggdll , @FozerG  или такое в пределах нормы?)

**Comment by eggdll** [comment]
я сделал его сам, различия видны, до этого даже не видел

**Comment by FozerG** [comment]
Претензия в том, что логотип немного похож? Вау, удивил. Мы находимся на GitHub и разрабатываем софт по свободным лицензиям (хотя некоторые выбирают менее свободные лицензии). И создавать Issues с таким текстом, как будто у тебя украли миллион долларов, выглядит как минимум некрасиво. Как сказал автор иконки @eggdll, никто у тебя её не крал, и изменения заметны. Наша иконка мне нравится больше 🫡
