### ISSUE TITLE
Ошибка через некоторое время использования. 

### ISSUE THREAD

**Issue by FreemoV** [FozerG/WinYandexMusicRPC#19]
https://imgur.com/a/9Yv6tCy

**Comment by FozerG** [comment]
Это не ожидаемое поведение, скрипт не должен завершаться при этой ошибке. Будет исправлено ❤️

**Comment by FozerG** [comment]
[Исправлено ](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9)
