### ISSUE TITLE
Через браузер не работает.

### ISSUE THREAD

**Issue by FreemoV** [FozerG/WinYandexMusicRPC#20]
Через браузер не работает. 
Хотя заявлено: Не ограничен использованием Яндекс Музыки, музыку можно слушать хоть из ВКонтакте ✅
Работает как с браузерами так и с приложениями ✅

Может быть это я чего не понимаю и использую то что надо по другому? 
https://youtu.be/tLHUF9zTnTY

Выпуск	Windows 11 Pro
Версия	23H2
Дата установки	‎26.‎02.‎2024
Сборка ОС	22635.3570
Взаимодействие	Windows Feature Experience Pack 1000.22700.1009.0

Процессор	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Оперативная память	16,0 ГБ
Тип системы	64-разрядная операционная система, процессор x64
Перо и сенсорный ввод	Для этого монитора недоступен ввод с помощью пера и сенсорный ввод

**Comment by FozerG** [comment]
Может дело в Яндекс браузере? Попробуй запустить музыку в браузере и перейти на экран блокировки в windows (WIN + L) и посмотреть есть ли в углу информация о мультимедии

**Comment by FreemoV** [comment]
Понял, винда не выводит мультимедию через яндекс, а скрипт работает через неё.
