### ISSUE TITLE
Выдаёт ошибку, если при сворачивании в трей, не увидит процесс яндекс музыки.

### ISSUE THREAD

**Issue by FreemoV** [FozerG/WinYandexMusicRPC#21]
https://youtu.be/4EZBjcvxSjI

**Comment by FozerG** [comment]
Это происходит если тыкать по окну до инициалзации скрипта. Лучше не трогать эти окна, сейчас они работают на очень корявых костылях 🫡 

Есть идеи насчет этого, позже попробую

**Comment by FozerG** [comment]
Коментарий выше о первой части ролика когда скрипт завис :)

А ошибка это дубликат #19 скорее

**Comment by FreemoV** [comment]
Так же завершает процесс если дс не открыт: https://imgur.com/a/x8lfDKC
Было бы круто, если бы ты добавил что то вроде проверки в свёрнутом режиме и что бы он не завершал процесс, а то я его поставил на автозапуск, но таким образом он не работает как я хотел.

**Comment by FozerG** [comment]
> Так же завершает процесс если дс не открыт: https://imgur.com/a/x8lfDKC Было бы круто, если бы ты добавил что то вроде проверки в свёрнутом режиме и что бы он не завершал процесс, а то я его поставил на автозапуск, но таким образом он не работает как я хотел.

[Готово](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9)
