### ISSUE TITLE
Пользовательский статус "Слушает" вместо "Играет в игру"

### ISSUE THREAD

**Issue by scpsltest** [FozerG/WinYandexMusicRPC#22]
можно ли заменить надпись "играет в игру" на что-то по типу "слушает" было бы прикольно это видеть т.к будет более лаконично
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/152562652/f746ada3-e67e-4c30-b4a9-3057ae7094d5)

**Comment by eggdll** [comment]
вроде невозможно

**Comment by AlexVin-Dev** [comment]
> вроде невозможно

Можно

**Comment by scpsltest** [comment]
будет хорошо если добавят эту функцию

**Comment by AlexVin-Dev** [comment]
> будет хорошо если добавят эту функцию

Будет время. Напиши небольшой код, чтобы автору было легче.

**Comment by scpsltest** [comment]
буду премного благодарен

**Comment by FozerG** [comment]
Это невозможно, только Spotify обладает такой возможностью благодаря собственной интеграции с Discord.

**Comment by scpsltest** [comment]
это очень грустно, я думал можно ведь человек выше написал что даст основу кода для кастомного статуса

**Comment by FozerG** [comment]
Ну как я сказал, это не возможно. Так что не знаю что он даст :)

**Comment by FozerG** [comment]
Обновление информации: Раньше такой возможности не было (и библиотека которую я использую так не умеет), сейчас это возможно но в таком случае статус урезан (без показа времени) 

Пример: 

![image](https://github.com/FozerG/WinYandexMusicRPC/assets/78788357/8ffb67ef-8c14-48f2-9131-30ab52156c2b)

**Comment by FozerG** [comment]
Это будет требовать использование веб-сокетов и личного Discord токена. Я не думаю, что это того стоит 🥺

**Comment by AlexVin-Dev** [comment]
Да я помню, что обещал. Но прочитав, что скорее всего может не работать так как может не воспроизвести описание, какая играет музыка. 

`await bot.change_presence(activity=discord.CustomActivity(name='текст' ,emoji='смайлик'))`

**Comment by FozerG** [comment]
Итак, я нашёл несколько свободных дней и решил попробовать воплотить эту идею.

Я использовал три разных метода:

- [discord.py-self](https://github.com/dolfies/discord.py-self)
- [discord.js-selfbot-v13](https://www.npmjs.com/package/discord.js-selfbot-v13) (пробовал тестировать на JavaScript)
- Собственная реализация WebSocket.

Документация везде очень расплывчатая и огромная, поэтому всё приходилось делать на ощупь. Вот максимальный результат, которого я смог достичь:

![Screenshot_471](https://github.com/FozerG/WinYandexMusicRPC/assets/78788357/f3372569-eeec-4e9d-b531-5779a30aace5)

К сожалению, мы теряем много функциональности по сравнению с текущим RPC, таких как кнопки, длительность трека, статус паузы и обложка.

Особенно много времени я потратил на попытки разобраться с обложкой, но безуспешно. Кто то пишет, что динамические URL не поддерживаются, другие — что поддерживаются, но при этом не работают. В итоге, всё остаётся расплывчатым и непонятным, и это относится ко всем трём методам.

Поэтому я, лично, прекращаю попытки реализации этой идеи. Это принесет больше проблем и неудобств, чем пользы. Кроме того, не забывайте, что всё это работает через личный токен Discord :)

Если кто-то сможет реализовать подгрузку динамических обложек через WebSocket или любые библиотеки, буду рад видеть ваш pull request или сообщения здесь.

**Comment by FreemoV** [comment]
может сделать пока типа такова? https://imgur.com/a/Xs7dl9F . Но я думаю это будет смотриеся кринова и не вписываться

**Comment by FreemoV** [comment]
Хз возможно тупа мосор с нейросети, но может поможет. 
Для реализации функции отображения статуса "слушает" и динамических обложек в Discord Rich Presence, воспользуемся Python и библиотекой `pypresence`, а также рассмотрим использование веб-сокетов и личного токена Discord. Давайте разберём основные шаги:

### Шаг 1: Установка необходимых библиотек

Установите `pypresence`:

```sh
pip install pypresence
```

### Шаг 2: Получение клиентского ID и подготовка изображений

1. Перейдите в [Discord Developer Portal](https://discord.com/developers/applications).
2. Создайте новое приложение или используйте существующее.
3. Получите `client_id`.
4. В разделе "Rich Presence" добавьте изображения для обложек.

### Шаг 3: Пример кода с динамическими обложками и статусом "слушает"

```python
import pypresence
import time

client_id = 'YOUR_CLIENT_ID'  # Замените на ваш клиентский ID
RPC = pypresence.Presence(client_id)
RPC.connect()

def update_presence(track, artist, album, large_image_key, small_image_key):
    RPC.update(
        details=f"Слушает: {track}",
        state=f"Исполнитель: {artist}",
        large_image=large_image_key,
        large_text=album,
        small_image=small_image_key,
        small_text="Yandex Music",
        start=time.time()
    )

# Обновите трек динамически
track_info = {
    "track": "Example Track",
    "artist": "Example Artist",
    "album": "Example Album",
    "large_image_key": "large_image_key",
    "small_image_key": "small_image_key"
}

while True:
    update_presence(**track_info)
    time.sleep(15)  # Обновление каждые 15 секунд
```

### Шаг 4: Использование WebSocket и личного токена Discord

Для этого понадобится использовать библиотеку `websockets` и ваш личный токен Discord. **Использование личного токена может нарушать правила Discord, будьте осторожны.**

1. Установите `websockets`:

    ```sh
    pip install websockets
    ```

2. Пример использования:

```python
import websockets
import asyncio
import json
import time

token = 'YOUR_DISCORD_TOKEN'

async def send_rpc():
    async with websockets.connect('wss://gateway.discord.gg/?v=6&encoding=json') as ws:
        hello = await ws.recv()
        heartbeat_interval = json.loads(hello)['d']['heartbeat_interval'] / 1000

        # Авторизация
        auth = {
            "op": 2,
            "d": {
                "token": token,
                "properties": {
                    "$os": "windows",
                    "$browser": "chrome",
                    "$device": "pc"
                }
            }
        }
        await ws.send(json.dumps(auth))

        while True:
            payload = {
                "op": 3,
                "d": {
                    "since": None,
                    "activities": [{
                        "name": "Yandex Music",
                        "type": 2,  # 2 - слушает
                        "details": "Слушает Example Track",
                        "state": "Исполнитель: Example Artist",
                        "assets": {
                            "large_image": "large_image_key",
                            "large_text": "Example Album",
                            "small_image": "small_image_key",
                            "small_text": "Yandex Music"
                        },
                        "timestamps": {
                            "start": int(time.time())
                        }
                    }],
                    "status": "online",
                    "afk": False
                }
            }
            await ws.send(json.dumps(payload))
            await asyncio.sleep(heartbeat_interval)

asyncio.get_event_loop().run_until_complete(send_rpc())
```

### Заключение

Эти примеры показывают, как обновлять статус в Rich Presence и использовать динамические обложки. Настройте их под свои нужды и убедитесь, что используете только легальные методы работы с токенами Discord.
Для того чтобы отображалось, что человек слушает музыку, а не играет в игру в Discord, нужно использовать тип активности `2` (Listening). В приведенном выше примере с использованием WebSocket это учитывается:

```python
payload = {
    "op": 3,
    "d": {
        "since": None,
        "activities": [{
            "name": "Yandex Music",
            "type": 2,  # 2 - слушает
            "details": "Слушает Example Track",
            "state": "Исполнитель: Example Artist",
            "assets": {
                "large_image": "large_image_key",
                "large_text": "Example Album",
                "small_image": "small_image_key",
                "small_text": "Yandex Music"
            },
            "timestamps": {
                "start": int(time.time())
            }
        }],
        "status": "online",
        "afk": False
    }
}
```

Использование `type: 2` указывает, что пользователь слушает музыку, и должно корректно отображаться в статусе Discord как "слушает". Убедитесь, что ключи изображений загружены в Discord Developer Portal.

**Comment by FreemoV** [comment]
### Уточнение по динамическим обложкам

Discord Rich Presence имеет ограничения на использование динамических URL для изображений. Однако, вы можете обновлять изображения, заранее загруженные в Discord Developer Portal, используя их ключи.

### Полный пример кода с использованием WebSocket и pypresence

1. **Установите необходимые библиотеки:**

    ```sh
    pip install pypresence websockets
    ```

2. **Пример использования pypresence для обновления статуса "слушает" с динамическими обложками:**

    ```python
    import pypresence
    import time

    client_id = 'YOUR_CLIENT_ID'  # Замените на ваш клиентский ID
    RPC = pypresence.Presence(client_id)
    RPC.connect()

    def update_presence(track, artist, album, large_image_key, small_image_key):
        RPC.update(
            details=f"Слушает: {track}",
            state=f"Исполнитель: {artist}",
            large_image=large_image_key,
            large_text=album,
            small_image=small_image_key,
            small_text="Yandex Music",
            start=time.time()
        )

    # Обновите трек динамически
    track_info = {
        "track": "Example Track",
        "artist": "Example Artist",
        "album": "Example Album",
        "large_image_key": "large_image_key",
        "small_image_key": "small_image_key"
    }

    while True:
        update_presence(**track_info)
        time.sleep(15)  # Обновление каждые 15 секунд
    ```

3. **Пример использования WebSocket для обновления статуса:**

    ```python
    import websockets
    import asyncio
    import json
    import time

    token = 'YOUR_DISCORD_TOKEN'

    async def send_rpc():
        async with websockets.connect('wss://gateway.discord.gg/?v=6&encoding=json') as ws:
            hello = await ws.recv()
            heartbeat_interval = json.loads(hello)['d']['heartbeat_interval'] / 1000

            # Авторизация
            auth = {
                "op": 2,
                "d": {
                    "token": token,
                    "properties": {
                        "$os": "windows",
                        "$browser": "chrome",
                        "$device": "pc"
                    }
                }
            }
            await ws.send(json.dumps(auth))

            while True:
                payload = {
                    "op": 3,
                    "d": {
                        "since": None,
                        "activities": [{
                            "name": "Yandex Music",
                            "type": 2,  # 2 - слушает
                            "details": "Слушает Example Track",
                            "state": "Исполнитель: Example Artist",
                            "assets": {
                                "large_image": "large_image_key",
                                "large_text": "Example Album",
                                "small_image": "small_image_key",
                                "small_text": "Yandex Music"
                            },
                            "timestamps": {
                                "start": int(time.time())
                            }
                        }],
                        "status": "online",
                        "afk": False
                    }
                }
                await ws.send(json.dumps(payload))
                await asyncio.sleep(heartbeat_interval)

    asyncio.get_event_loop().run_until_complete(send_rpc())
    ```

### Заключение

Эти примеры помогут вам настроить статус "слушает" и использовать динамические обложки.

**Comment by FozerG** [comment]
К сожалению, chatgpt не понимает всех тонкостей API Discord. Впрочем, мало кто понимает.

**Comment by AlexVin-Dev** [comment]
> К сожалению, chatgpt не понимает всех тонкостей API Discord. Впрочем, мало кто понимает.

Я с тобой соглашусь

**Comment by Kefisto** [comment]
![изображение](https://github.com/FozerG/WinYandexMusicRPC/assets/99140797/03001e87-d1e9-4297-bb5a-0a922eab9926)
По сути возможно сделать так, таймер возможен (наверное), но мой старый код к сожалению его более не возможно.

**Comment by FozerG** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/99140797/345656950-03001e87-d1e9-4297-bb5a-0a922eab9926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTQ4NzksIm5iZiI6MTcyMDA1NDU3OSwicGF0aCI6Ii85OTE0MDc5Ny8zNDU2NTY5NTAtMDMwMDFlODctZDFlOS00Mjk3LWJiNWEtMGE5MjJlYWI5OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwNTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzQ0MDVjZjJkOGQ5YWI5MzI1NzQ5MTAyNGIzZGM3NDQ3ZmVlMTkwYzlhYzBlMjE0NjM3MjhiN2U5MmFiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VDCo8HAq9CisPYh86LCfTkU-_TIwEdbpI6onFDCjZyY) По сути возможно сделать так, таймер возможен (наверное), но мой старый код к сожалению его более не отображает.

А где можно посмотреть код? :)

**Comment by Kefisto** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/99140797/345656950-03001e87-d1e9-4297-bb5a-0a922eab9926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTQ4NzksIm5iZiI6MTcyMDA1NDU3OSwicGF0aCI6Ii85OTE0MDc5Ny8zNDU2NTY5NTAtMDMwMDFlODctZDFlOS00Mjk3LWJiNWEtMGE5MjJlYWI5OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwNTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzQ0MDVjZjJkOGQ5YWI5MzI1NzQ5MTAyNGIzZGM3NDQ3ZmVlMTkwYzlhYzBlMjE0NjM3MjhiN2U5MmFiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VDCo8HAq9CisPYh86LCfTkU-_TIwEdbpI6onFDCjZyY) По сути возможно сделать так, таймер возможен (наверное), но мой старый код к сожалению его более не отображает.
> 
> А где можно посмотреть код? :)

реализовано через токен, от этого нет смысла (хотя можно сделать авто ввод токена)

**Comment by FozerG** [comment]
> > > ![изображение](https://private-user-images.githubusercontent.com/99140797/345656950-03001e87-d1e9-4297-bb5a-0a922eab9926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTQ4NzksIm5iZiI6MTcyMDA1NDU3OSwicGF0aCI6Ii85OTE0MDc5Ny8zNDU2NTY5NTAtMDMwMDFlODctZDFlOS00Mjk3LWJiNWEtMGE5MjJlYWI5OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwNTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzQ0MDVjZjJkOGQ5YWI5MzI1NzQ5MTAyNGIzZGM3NDQ3ZmVlMTkwYzlhYzBlMjE0NjM3MjhiN2U5MmFiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VDCo8HAq9CisPYh86LCfTkU-_TIwEdbpI6onFDCjZyY) По сути возможно сделать так, таймер возможен (наверное), но мой старый код к сожалению его более не отображает.
> > 
> > 
> > А где можно посмотреть код? :)
> 
> реализовано через токен, от этого нет смысла (хотя можно сделать авто ввод токена)

Понятное дело :) Уже для яндекса реализована система, думаю для дискорда так же могу адаптировать

**Comment by saberkovich** [comment]
> Прошу прощения, что в каких-то вещах не шарю: вы пробовали связаться с командой Я.Музыки и передать им код? Может быть они что-то сделают со своей стороны? Например, свяжутся с командой Дискорда для полнофункциональной фичи с отображением статуса как в Спотике?

Подобное пожелание уже писали на форуме предложений - https://yandexmusic.userecho.com/communities/45/topics/2672-integratsiya-s-discord?page=20

4 года назад... До сих пор не реализовали

**Comment by saberkovich** [comment]
> > > ![изображение](https://private-user-images.githubusercontent.com/99140797/345656950-03001e87-d1e9-4297-bb5a-0a922eab9926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTQ4NzksIm5iZiI6MTcyMDA1NDU3OSwicGF0aCI6Ii85OTE0MDc5Ny8zNDU2NTY5NTAtMDMwMDFlODctZDFlOS00Mjk3LWJiNWEtMGE5MjJlYWI5OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwNTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzQ0MDVjZjJkOGQ5YWI5MzI1NzQ5MTAyNGIzZGM3NDQ3ZmVlMTkwYzlhYzBlMjE0NjM3MjhiN2U5MmFiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VDCo8HAq9CisPYh86LCfTkU-_TIwEdbpI6onFDCjZyY) По сути возможно сделать так, таймер возможен (наверное), но мой старый код к сожалению его более не отображает.
> > 
> > 
> > А где можно посмотреть код? :)
> 
> реализовано через токен, от этого нет смысла (хотя можно сделать авто ввод токена)

Брат скинь код) Очень надеемся на тебя @Kefisto

**Comment by FozerG** [comment]
В разработке :)

![image](https://github.com/user-attachments/assets/85589942-24bd-4f25-a45d-d48eff447a08)

**Comment by FozerG** [comment]
Я реализовал этот функционал в версии [2.2.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.2.1).

![image](https://github.com/user-attachments/assets/751c689d-65fd-47ed-b781-eb32d7831daf)
