### ISSUE TITLE
Ошибка спустя некоторое время, после запуска

### ISSUE THREAD

**Issue by FreemoV** [FozerG/WinYandexMusicRPC#23]
https://imgur.com/a/kdQpuCU

**Comment by FozerG** [comment]
Проблема связана с треком: его альбом назван одним символом. Это не критично и будет исправлено в будущем ❤️

**Comment by FozerG** [comment]
Исправлено в [1.9.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9.1)
