### ISSUE TITLE
Закрывается без каких-либо сообщений

### ISSUE THREAD

**Issue by OwlAndDot** [FozerG/WinYandexMusicRPC#24]
Версия 1.7 работает, более новые - нет, происходит то, что на видео(версия последняя). 
https://youtu.be/6frkIpbebeo

**Comment by FozerG** [comment]
В телеграм будет удобнее?

**Comment by OwlAndDot** [comment]
Угу, id свой давать?

**Comment by FozerG** [comment]
Давай

**Comment by OwlAndDot** [comment]
https://t.me/Vlad_O_Z

**Comment by FozerG** [comment]
Для тех, кто читает: Проблема заключалась в урезанной версии Windows 10, где не работал conhost.exe. Я исправил это, перестав использовать conhost.exe на Windows 10. Теперь он используется только на Windows 11. Всё же ребята используйте нормальные версии Windows 🫡
