### ISSUE TITLE
Перестает работать скрипт когда включается определенный артист

### ISSUE THREAD

**Issue by toshundris1** [FozerG/WinYandexMusicRPC#25]
Заметил, что скрипт перестает работать после того, как включается трек от определенного артиста, в моем случае это 2hollis. После этого скрипт приходится в ручную перезапускать. Сообщение в консоли прикрепил
![WinYandexMusicRPC-1-9_ORxh9fp5sS](https://github.com/FozerG/WinYandexMusicRPC/assets/58503673/9532980f-e65f-49d5-a8d6-ed910f925001)

Возможно следует исправить конкретно этот баг, либо добавить возможность перезапустить скрипт из трея.

**Comment by FozerG** [comment]
Исправлено в [1.9.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9.1). Спасибо ❤️

**Comment by toshundris1** [comment]
большое спасибо!
