### ISSUE TITLE
Скрипт перестает работать при включении видео на ютуб

### ISSUE THREAD

**Issue by toshundris1** [FozerG/WinYandexMusicRPC#26]
Использую яндекс музыку исключительно в браузере, при включении видео в этом же браузере скрипт переключается на ютубовское видео и перестает выводить статус. При повторном включении музыки все встает на места, прикрепил пример ниже
![WinYandexMusicRPC-1-9_cuJOnlkitH](https://github.com/FozerG/WinYandexMusicRPC/assets/58503673/813b7f84-0317-4168-8ae1-20e6dffe3bf1)

**Comment by FozerG** [comment]
Так работают браузеры и Windows Api. Никак не исправить, потому что скрипт использует только информацию, которую передает Windows API. Почему браузеры передают в API медиаплеер видеоролики с YouTube - это другой вопрос. Лично мне это не мешает, так как я не слушаю музыку одновременно с просмотром видео на YouTube.
