### ISSUE TITLE
can't find some tracks

### ISSUE THREAD

**Issue by barman228** [FozerG/WinYandexMusicRPC#27]
![Снимок экрана 2024-05-28 220742](https://github.com/FozerG/WinYandexMusicRPC/assets/58826246/6ba9568e-16ed-4734-b003-fd51e7f105f9)

**Comment by barman228** [comment]
> Я не смог найти Radio Edit этой песни в Яндекс Музыке. Слушаешь музыку на Яндекс Музыке? Если нет, возможно, поможет отключение флага strong_find.

Слушаю в Яндекс Музыке, я уже отключил эту функцию и всё вроде работает

**Comment by barman228** [comment]
И ещё почему то он захватывает видео из Youtube, странно, но хорошо что оно не отображается.

**Comment by FozerG** [comment]
С отключённым strong_find я бы осторожнее смотрел видеоролики на YouTube, потому что поиск на Яндекс Музыке непредсказуем. Еще, я писал об этом в #26.

**Comment by barman228** [comment]
> С отключённым strong_find я бы осторожнее смотрел видеоролики на YouTube, потому что поиск на Яндекс Музыке непредсказуем. Еще, я писал об этом в #26.

Обнаружил ещё проблему, при просмотре видео приходится выключать программу, т.к. жрёт 30-60% ЦП, видео начиная от 2к смотреть уже невозможно, каждый раз приходится выключать её чтобы спокойно посмотреть 2к - 4к видео.
P.S.  Я сначала подумал у меня браузер умирает ;)

**Comment by FozerG** [comment]
Нагрузка появляется только при просмотре видео? Я не замечал подобных проблем. Пожалуйста, отправь характеристики компьютера и скриншот из диспетчера задач.

**Comment by barman228** [comment]
> Нагрузка появляется только при просмотре видео? Я не замечал подобных проблем. Пожалуйста, отправь характеристики компьютера и скриншот из диспетчера задач.

Эта проблема появляется случайно, если поймаю сделаю скрин.

**Comment by barman228** [comment]
![Снимок экрана 2024-05-31 091226](https://github.com/FozerG/WinYandexMusicRPC/assets/58826246/3fd79ccc-43b8-4d0a-9970-4bbc9e74a61f)
![Снимок экрана 2024-05-31 091400](https://github.com/FozerG/WinYandexMusicRPC/assets/58826246/631e03ca-5d39-48a8-93d3-e1afcf50f2d4)
Поймал всё таки момент, вот как то так, характеристики видно на втором скрине.

**Comment by FozerG** [comment]
Честно говоря у меня нет идей, как и желания вылавливать такую редкую проблему. Ну и будем честны - процессор с 4 потоками тоже является небольшой проблемой :)

В коде нет ничего криминального, и возможно, причина проблемы в одной из десятка библиотек, за которые я не могу отвечать.

**Comment by toshundris1** [comment]
> ![Снимок экрана 2024-05-31 091226](https://private-user-images.githubusercontent.com/58826246/335423879-3fd79ccc-43b8-4d0a-9970-4bbc9e74a61f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTU0ODgsIm5iZiI6MTcxNzQ5NTE4OCwicGF0aCI6Ii81ODgyNjI0Ni8zMzU0MjM4NzktM2ZkNzljY2MtNDNiOC00ZDBhLTk5NzAtNGJiYzllNzRhNjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDA5YWRlYWI0OGEwOTBhYTg5ZGU5MDk1OGI1YmM2NmY5YjhkZTMwYmYyYTI3NWY2YWVkMGI0MTY4Yjc0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pu_W0NyqewIC1pUAp0w7C8YYMcEQSVFlmEw4e0mhjEs) ![Снимок экрана 2024-05-31 091400](https://private-user-images.githubusercontent.com/58826246/335423941-631e03ca-5d39-48a8-93d3-e1afcf50f2d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTU0ODgsIm5iZiI6MTcxNzQ5NTE4OCwicGF0aCI6Ii81ODgyNjI0Ni8zMzU0MjM5NDEtNjMxZTAzY2EtNWQzOS00OGE4LTkzZDMtZTFhZmNmNTBmMmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YmIzMzlmZTRiZjgzNDYyYmZlZjZmNGY2NDIxZWRiMjQ4OWVlYjg1N2ZhN2I4ZmM0MzVkOTRhNWJhYTg4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2dVcad8-uwTrahD56ZNlS1QTXVxb8T_d-qjNP3Sxrq8) Поймал всё таки момент, вот как то так, характеристики видно на втором скрине.

кстати, вчера я тоже поймал такой баг. процессор грузился программой на сто процентов

**Comment by FozerG** [comment]
> > ![Снимок экрана 2024-05-31 091226](https://private-user-images.githubusercontent.com/58826246/335423879-3fd79ccc-43b8-4d0a-9970-4bbc9e74a61f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTU0ODgsIm5iZiI6MTcxNzQ5NTE4OCwicGF0aCI6Ii81ODgyNjI0Ni8zMzU0MjM4NzktM2ZkNzljY2MtNDNiOC00ZDBhLTk5NzAtNGJiYzllNzRhNjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDA5YWRlYWI0OGEwOTBhYTg5ZGU5MDk1OGI1YmM2NmY5YjhkZTMwYmYyYTI3NWY2YWVkMGI0MTY4Yjc0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pu_W0NyqewIC1pUAp0w7C8YYMcEQSVFlmEw4e0mhjEs) ![Снимок экрана 2024-05-31 091400](https://private-user-images.githubusercontent.com/58826246/335423941-631e03ca-5d39-48a8-93d3-e1afcf50f2d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTU0ODgsIm5iZiI6MTcxNzQ5NTE4OCwicGF0aCI6Ii81ODgyNjI0Ni8zMzU0MjM5NDEtNjMxZTAzY2EtNWQzOS00OGE4LTkzZDMtZTFhZmNmNTBmMmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5NTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YmIzMzlmZTRiZjgzNDYyYmZlZjZmNGY2NDIxZWRiMjQ4OWVlYjg1N2ZhN2I4ZmM0MzVkOTRhNWJhYTg4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2dVcad8-uwTrahD56ZNlS1QTXVxb8T_d-qjNP3Sxrq8) Поймал всё таки момент, вот как то так, характеристики видно на втором скрине.
> 
> кстати, вчера я тоже поймал такой баг. процессор грузился программой на сто процентов

В консоли при этом ничего такого не было?
