### ISSUE TITLE
Играет в Yandex.Music

### ISSUE THREAD

**Issue by AlexGreat007** [FozerG/WinYandexMusicRPC#28]
Привет. А возможно сделать так, чтобы в статусе отображалось не `Играет в Yandex.Music`, а `Слушает Яндекс Музыку`?

P.S. Чтобы не создавать новый тикет, также тут хочу спросить: а как настроить автозапуск консольки с включением компьютера?

**Comment by FozerG** [comment]
О статусе подробно расписал в #22. 

Касательно автозапуска: встроенной функции для этого нет, поэтому нужно добавить программу в автозапуск самостоятельно [любым удобным способом](https://lifehacker.ru/kak-dobavit-programmu-v-avtozagruzku-windows-10/).
