### ISSUE TITLE
[WinYandexMusicRPC] -> Discord was closed

### ISSUE THREAD

**Issue by FreemoV** [FozerG/WinYandexMusicRPC#29]
Если есть возможность и идеи, хотелось бы видеть, что бы при закрытии DS одно не вылетало.

**Comment by FozerG** [comment]
В будущем обновлении попробую реализовать :)

**Comment by FozerG** [comment]
Логика изменена в [новой версии 2.0](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.0)
