### ISSUE TITLE
предложение: невидимое окно

### ISSUE THREAD

**Issue by deadcxap** [FozerG/WinYandexMusicRPC#3]
У себя сделал экзешник в виде скрытого окна, чтобы лишняя консолька не мозолила глаза:
```
pip install pyinstaller
pyinstaller --noconfirm --onefile --windowed --name "WinYandexMusicRPC" --hide-console "hide-early"  "E:/WinYandexMusicRPC-main/main.py"
```
Как найду способ при этом создавать иконку в трее с опцией закрытия приложения - дополню.

**Comment by FozerG** [comment]
Можно сделать скрытым окно консоли, но иконка в трее всё таки необходима - что бы понимать что скрипт работает, и в случаее чего читать логи. Это уже в TODO, но пока что не могу найти мотивации на это 😢

**Comment by AlexGreat007** [comment]
Привет. Тоже подумал, что терминал бы в фоне не помешал, а то мозолится на панельке задач. А вообще спасибо за скрипт :)
