### ISSUE TITLE
discord is launched but not ready for rich presence

### ISSUE THREAD

**Issue by banochka01** [FozerG/WinYandexMusicRPC#30]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/153225906/6aa11203-15ef-4c03-a466-219ad971a83d)

**Comment by FozerG** [comment]
Всегда такая ошибка? Получалось запустить успешно? Дискорд запущен и авторизирован? Используешь бета версию дискорда? Попробуй эту [версию](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.7)

**Comment by FozerG** [comment]
Должно быть исправлено в [новой версии 2.0](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.0)
