### ISSUE TITLE
Не скачивается новый .exe файл

### ISSUE THREAD

**Issue by Sijhipe** [FozerG/WinYandexMusicRPC#31]
Windows блокирует скачку exe файла
![Screenshot_97](https://github.com/FozerG/WinYandexMusicRPC/assets/168995852/b8b1c7b2-cdd5-4f8b-af07-2b1c059260a8)

**Comment by FozerG** [comment]
Подробнее -> Выполнить.

Это не блокировка, а предупреждение о том, что файл .exe не подписан. Это нормальная практика.
