### ISSUE TITLE
Программка сбоит

### ISSUE THREAD

**Issue by toshundris1** [FozerG/WinYandexMusicRPC#33]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/58503673/7531e7b3-8067-45c3-a8d9-c52a8f43dfbb)

текст лога скопировать не получается

**Comment by toshundris1** [comment]
со всеми, но само починилось как то. поэтому пока не жалуюсь

**Comment by FozerG** [comment]
Может был включен впн? #16

**Comment by toshundris1** [comment]
кстати да, скорее всего так и было. спасибо
