### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by FreemoV** [FozerG/WinYandexMusicRPC#34]
https://imgur.com/a/ioTSmDv

**Comment by FozerG** [comment]
Это при использовании с автозапуска? В дискорде залогинен?

**Comment by FreemoV** [comment]
Да

**Comment by FozerG** [comment]
В обновлении попробую изменить логику

**Comment by FozerG** [comment]
Логика изменена в [новой версии 2.0](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.0)
