### ISSUE TITLE
статус не уходит

### ISSUE THREAD

**Issue by grigoran420** [FozerG/WinYandexMusicRPC#35]
Было бы неплохо сделать функцию, которая убирала бы статус, если, например, человек перестал слушать музыку. Чтоб каждый раз не закрывать приложение.

**Comment by FozerG** [comment]
Через 5 минут паузы статус убирается

**Comment by grigoran420** [comment]
ну... я закрыл приложение и ничего не изменилось

**Comment by grigoran420** [comment]
приложение музыки

**Comment by FozerG** [comment]
При закрытии приложения яндекс музыка статус должен пропасть. Какой показывает статус?

**Comment by grigoran420** [comment]
![Безымянный](https://github.com/FozerG/WinYandexMusicRPC/assets/43644174/51f8034b-4e93-4f6a-9c93-217146eb58c4)
![Снимок экрана 2024-06-15 184256](https://github.com/FozerG/WinYandexMusicRPC/assets/43644174/8ada72b5-4607-457d-8347-b502d34782b5)

Кстати еще обнаружилось, что при перематывании трека время не меняется, либо если меняется, но я не дождался

**Comment by FozerG** [comment]
Старое приложение яндекс муызки не поддерживает перемотку, возможно и из за этого не пропадает трек. Попробуй новую версию
