### ISSUE TITLE
не работает скрипт

### ISSUE THREAD

**Issue by toshundris1** [FozerG/WinYandexMusicRPC#36]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/58503673/8815da57-7427-48fa-8cd5-eb3db9111a48)

все работало до того, как вчера поставил расширение для хрома https://chromewebstore.google.com/detail/%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF/gcfheefljlblchcfjlknidfimnfillec

**Comment by FozerG** [comment]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/78788357/456a6040-4c36-4dc9-815f-861dae5fdb43)
