### ISSUE TITLE
Ошибка с кодом -2147023836 указанная служба не установлена  

### ISSUE THREAD

**Issue by makargart** [FozerG/WinYandexMusicRPC#37]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/82509010/f30d92ac-bf11-4528-8a8f-8a7555d8ec2b)

**Comment by FozerG** [comment]
Какая версия Windows? Не урезанная версия с торрента?

**Comment by makargart** [comment]
win 11 lite

**Comment by makargart** [comment]
> Какая версия Windows? Не урезанная версия с торрента?

Хотя python 3.10 и 3.12 стоит яндекс музыка с сайта браузере всё открыто.

**Comment by FozerG** [comment]
Вот и проблема: в урезанных версиях Windows winsdk не работает, так как в этих системах просто отсутствуют необходимые API. Почему вы не используйте полноценные версии Windows?

**Comment by makargart** [comment]
> Вот и проблема: в урезанных версиях Windows winsdk не работает, так как в этих системах просто отсутствуют необходимые API. Почему вы не используйте полноценные версии Windows?

а обычная она не оптимизированная и всяким хламом мне этого не нужно поставил самодельную сборку и всё.

**Comment by makargart** [comment]
Если знаешь, можешь скинуть список API нужных.

**Comment by FozerG** [comment]
> Author



> > Вот и проблема: в урезанных версиях Windows winsdk не работает, так как в этих системах просто отсутствуют необходимые API. Почему вы не используйте полноценные версии Windows?
> 
> а обычная она не оптимизированная и всяким хламом мне этого не нужно поставил самодельную сборку и всё.

Ну вот тебе пример удаленного хлама - удаленное API которое не позволяет тебе пользоваться скриптом.

**Comment by FozerG** [comment]
> Если знаешь, можешь скинуть список API нужных.

GlobalSystemMediaTransportControlsSessionManager встроен в Windows (обычно🫡) и не доступен для скачивания отдельно
