### ISSUE TITLE
Отображение треков из браузера не работает (Яндекс и VK Музыка)

### ISSUE THREAD

**Issue by WolfRam1d** [FozerG/WinYandexMusicRPC#38]
У скрипта **не работает отображение треков из браузера**, как ВК-Музыка, так и Яндекс. Можно ли было как-нибудь это поправить? Было бы классно, чтобы работало отображение треков в статусе из браузера.
А если не получится - то тогда убрать из README заявления про браузер.
**Заранее спасибо!**

**Comment by FozerG** [comment]
Какой именно то браузер? :)

**Comment by WolfRam1d** [comment]
> Какой именно то браузер? :)

В основном Яндекс, но пробовал и Google Chrome. Ни один не работает.

**Comment by WolfRam1d** [comment]
> Работает в Microsoft Edge

Здорово, жаль, он мне не нужен)

**Comment by FozerG** [comment]
Google Chrome полностью поддерживается и проверен мной. Яндекс Браузер я не проверял. Что показывают логи программы при использовании Chrome? Появляется ли медиаплеер Windows в правом нижнем углу экрана, когда запускаешь музыку и переходишь в режим блокировки?

**Comment by WolfRam1d** [comment]
Сейчас перезапустил скрипт, всё заработало, текст ошибки в логах не запомнил.
Есть ли возможность ввести в поддержку Яндекс Браузер? Было бы классно, чтобы с Яндексом всё так же работало.

**Comment by FozerG** [comment]
> Сейчас перезапустил скрипт, всё заработало, текст ошибки в логах не запомнил. Есть ли возможность ввести в поддержку Яндекс Браузер? Было бы классно, чтобы с Яндексом всё так же работало.

Я не пользуюсь Яндекс Браузером, и раз он не работает, то, вероятно, не передает данные в Windows API. Как появится минутка, скачаю его и проверю.

**Comment by WolfRam1d** [comment]
> Я не пользуюсь Яндекс Браузером, и раз он не работает, то, вероятно, он не передает данные в Windows API. Как появится минутка, скачаю его и проверю.

Хорошо, спасибо.

**Comment by WolfRam1d** [comment]
@FozerG Thx. Из браузера заработало, рандомно заметил. Спасибо огромное!

**Comment by FozerG** [comment]
Из яндекс бразуера?

> @FozerG Thx. Из браузера заработало, рандомно заметил. Спасибо огромное!

**Comment by WolfRam1d** [comment]
> Из яндекс бразуера?

Именно

**Comment by FozerG** [comment]
Отлично 🥰
