### ISSUE TITLE
Срабатывает защита DRM

### ISSUE THREAD

**Issue by usconf** [FozerG/WinYandexMusicRPC#39]
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/123841942/42ad4a79-de5b-4080-b58d-2b0f7983797d)
OS: Windows 10 LTSC 21H2 (чистая, не сборка)
Браузер: Mozilla Firefox 127.0.1 (64-bit)
Python: 3.10.6
В Discord не отображается ничего (даже то, что я музыку слушаю, хотя оно захватывается скриптом судя по консоли)

Я не знаю что ещё добавить сюда. Надеюсь всё указал

**Comment by usconf** [comment]
Добавлю:
Я живу в Европе. Подключился к VPN в России, всё заработало. Можно ли это как-то пофиксить без использования VPN?
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/123841942/43ca3ecb-7bd7-4ccf-8662-47f1c8ed1afa)

**Comment by FozerG** [comment]
Да, но для этого нужно использование личного токена яндекс музыки. Если есть востребованность такой функции то могу сделать :)

**Comment by FozerG** [comment]
Привет! Реализовал бета версию, которая работает в странах, где Яндекс.Музыка доступна только с подпиской Плюс. Есть возможность протестировать?

**Comment by usconf** [comment]
> Привет! Реализовал бета версию, которая работает в странах, где Яндекс.Музыка доступна только с подпиской Плюс. Есть возможность протестировать?

Да, могу протестировать. Если ты хочешь для более удобного тестирования можем связаться через Telegram/VK. Ну либо здесь

**Comment by FozerG** [comment]
Поскольку файл слишком большой для отправки здесь, предлагаю Telegram. Отправь свой username, и я свяжусь с тобой.

> > Привет! Реализовал бета версию, которая работает в странах, где Яндекс.Музыка доступна только с подпиской Плюс. Есть возможность протестировать?
> 
> Да, могу протестировать. Если ты хочешь для более удобного тестирования можем связаться через Telegram/VK/Discord. Ну либо здесь

**Comment by usconf** [comment]
> Поскольку файл слишком большой для отправки здесь, предлагаю Telegram. Отправь свой username, и я свяжусь с тобой.
> 
> > > Привет! Реализовал бета версию, которая работает в странах, где Яндекс.Музыка доступна только с подпиской Плюс. Есть возможность протестировать?
> > 
> > 
> > Да, могу протестировать. Если ты хочешь для более удобного тестирования можем связаться через Telegram/VK/Discord. Ну либо здесь

Держи: https://t.me/andrey_daniluk

**Comment by FozerG** [comment]
> > Поскольку файл слишком большой для отправки здесь, предлагаю Telegram. Отправь свой username, и я свяжусь с тобой.
> > > > Привет! Реализовал бета версию, которая работает в странах, где Яндекс.Музыка доступна только с подпиской Плюс. Есть возможность протестировать?
> > > 
> > > 
> > > Да, могу протестировать. Если ты хочешь для более удобного тестирования можем связаться через Telegram/VK/Discord. Ну либо здесь
> 
> Держи: https://t.me/andrey_daniluk

![image](https://github.com/FozerG/WinYandexMusicRPC/assets/78788357/d16b37ac-fee2-4e28-ae82-1515037fd39c)

**Comment by usconf** [comment]
> > > Поскольку файл слишком большой для отправки здесь, предлагаю Telegram. Отправь свой username, и я свяжусь с тобой.
> > > > > Привет! Реализовал бета версию, которая работает в странах, где Яндекс.Музыка доступна только с подпиской Плюс. Есть возможность протестировать?
> > > > 
> > > > 
> > > > Да, могу протестировать. Если ты хочешь для более удобного тестирования можем связаться через Telegram/VK/Discord. Ну либо здесь
> > 
> > 
> > Держи: https://t.me/andrey_daniluk
> 
> ![image](https://private-user-images.githubusercontent.com/78788357/342400943-d16b37ac-fee2-4e28-ae82-1515037fd39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDU3NzIsIm5iZiI6MTcxOTI0NTQ3MiwicGF0aCI6Ii83ODc4ODM1Ny8zNDI0MDA5NDMtZDE2YjM3YWMtZmVlMi00ZTI4LWFlODItMTUxNTAzN2ZkMzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YjhjNGExOTA3ODcwOGM0MDIxMTg2MDg4ZTIzY2UxMDUwZDZmZDM0MTIwOTU1NmNkNmY5OTkzYzRiZDRiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tVu5w95SJL0Gpez6KFdPjZKIPRm4IHFHJBVXW90UhbQ)

Ой, сорри, забыл за это. Убрал

**Comment by FozerG** [comment]
[Исправлено в 2.1.4](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.1.4)
