### ISSUE TITLE
Ошибка "WinError -2147418110"

### ISSUE THREAD

**Issue by WolfRam1d** [FozerG/WinYandexMusicRPC#40]
Скрипт не работает, выдаёт ошибку "Вызов был отклонён фильтром сообщений"
Windows 10 Home v.22H2
Yandex Browser

![2024-06-19_23-10-04](https://github.com/FozerG/WinYandexMusicRPC/assets/173184064/3601cb9a-d978-4956-bef3-77aa05916bea)

**Comment by FozerG** [comment]
Постоянно так? Какая версия Windows? Модифицированая или урезанная версия Windows?

**Comment by WolfRam1d** [comment]
> Постоянно так? Какая версия Windows? Модифицированая или урезанная версия Windows?
Несколько (5) раз перезапускал скрипт. Насчёт урезанновсти или модифицированности версии Windows не знаю, просто взял с помощью специальной проги и установил на ПК.

**Comment by FozerG** [comment]
> Постоянно



> > Постоянно так? Какая версия Windows? Модифицированая или урезанная версия Windows?
> 
> Несколько (5) раз перезапускал скрипт. Насчёт урезанновсти или модифицированности версии Windows не знаю, просто взял с помощью специальной проги и установил на ПК.

До этого же работало? Это версия 2.0? Пробовал перезапускать ПК?

**Comment by WolfRam1d** [comment]
> До этого же работало? Это версия 2.0? Пробовал перезапускать ПК?

Проблема была и с 1.9.1. и с 2.0. Перезапуск сейчас попробую

**Comment by FozerG** [comment]
Ну что значит проблема была. Я хочу понять у тебя же получалось хоть раз запускать скрипт что бы статус выводился в дискорд?

**Comment by WolfRam1d** [comment]
Рестарт помог

**Comment by WolfRam1d** [comment]
Скрипт запускался и сразу выдавал ошибку, потом очищал трек и снова выдавал бесконечно ошибки. Статус не выводился и треки не регались в скрипте

**Comment by FozerG** [comment]
Интересно. Если повториться - напиши. Я не знаю как отследить такое :)
