### ISSUE TITLE
неправильное отображение времени музыки в RPC

### ISSUE THREAD

**Issue by MkasSASD** [FozerG/WinYandexMusicRPC#42]
Я Столкнулся с проблемой: что время не правильно отображается в статусе
Что я сделал что бы получить эту проблему: я запустил yandex music windows app from microsoft store и запустил RPC, после чего поставил музыку на повтор

Вот скриншот с логами скрипта:
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/43532096/4fdd9161-a346-49e0-aa67-d7aef2ff94e5)

OS: Windows 11 22H2
Браузер: не использую

**Comment by FozerG** [comment]
Старое приложение Яндекс Музыки не поддерживает эту функцию. Воспользуйся [новой версией](https://music.yandex.ru/download/).
