### ISSUE TITLE
WinError -2147418110 

### ISSUE THREAD

**Issue by WolfRam1d** [FozerG/WinYandexMusicRPC#43]
Я Столкнулся с проблемой: ошибка "Вызов был отклонен фильтром сообщений". 

Вот скриншот с логами скрипта:
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/173184064/338c6262-a77a-45ed-aa52-b7a074028933)

OS: Windows 10 22H2 (чистая, не сборка)
Браузер: Yandex Browser (64-bit)

**Comment by FozerG** [comment]
И снова привет, дай такой скрин 
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/78788357/e99d8467-4520-4ffe-bd70-97676f1c4eea)

**Comment by WolfRam1d** [comment]
> И снова привет, дай такой скрин. Перезапуск уже не помогает?

![image](https://github.com/FozerG/WinYandexMusicRPC/assets/173184064/04f4833f-071b-4b69-ad21-c0a2e5665f86)

Перезапуск помог, но не с первого раза.

**Comment by FozerG** [comment]
Когда ошибка повториться попробуй использовать [этот скрипт на чистом c# ](https://github.com/KOTOKOPOLb/Music-RPC/releases). И сообщи о результатах 😊
