### ISSUE TITLE
Не открывается

### ISSUE THREAD

**Issue by Kefisto** [FozerG/WinYandexMusicRPC#44]
Я Столкнулся с проблемой: Не открывается
Что я сделал что бы получить эту проблему: Кликнул туда, сюда, тудым.

Вот скриншот с логами скрипта:
Получить не могу
OS: Windows 11 Pro 23H2 (чистая, не сборка)
Браузер: Mozilla Firefox 127.0.1 (64-bit)
![изображение](https://github.com/FozerG/WinYandexMusicRPC/assets/99140797/b2017260-b964-4866-ad34-bff17e3b5f82)

**Comment by Kefisto** [comment]
Пару дней поработало и более не запускается, перезапуск не помогает.

**Comment by FozerG** [comment]
Попробуй скачать файл полностью заново и перенести его например на рабочий стол

**Comment by Kefisto** [comment]
Таже проблема

**Comment by FozerG** [comment]
Причин может быть много, но они не зависят от меня или скрипта.

- Антивирусное программное обеспечение может блокировать файлы.
- Windows заблокировала файлы.
- Файл поврежден, скрыт или удален антивирусом.
- Ярлык программы поврежден.
 - У вас нет разрешения на доступ к элементу, поскольку вы не являетесь администратором.

А эта ошибка появляется сразу без показа консоли?

> Таже проблема

**Comment by Kefisto** [comment]
- А эта ошибка появляется сразу без показа консоли?
Да

**Comment by Kefisto** [comment]
https://github.com/FozerG/WinYandexMusicRPC/assets/99140797/6cb5da4c-4186-4752-8417-231bcbaef077

иногда может открыться, но бесконечная инициализация

**Comment by FozerG** [comment]
Попробуй запустить `WinYandexMusicRPC.exe` здесь: `%TEMP%/WinYandexMusicRPC`

Или удали его из этой папки и попробуй запустить обычный скрипт еще раз.

**Comment by Kefisto** [comment]
через пару попыток запустилось, посмотрю на долго ли это

**Comment by FozerG** [comment]
Единственное, что меня немного беспокоит, это то, что у тебя пользователь находится в папке OneDrive. Но даже не знаю, что еще можно сделать в твоем случае :) Если проблема повторится, попробуй версию [2.0](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.0). В ней нет системы лаунчера.
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/78788357/9fdd93ab-96c7-44c8-aeb2-7a602aebf108)
