### ISSUE TITLE
WinError 5

### ISSUE THREAD

**Issue by Xlebuzik** [FozerG/WinYandexMusicRPC#45]
Я Столкнулся с проблемой: Discord is launched but not ready for Rich Presence

Скрин из консоли прилагаю
![изображение_2024-07-09_223332406](https://github.com/FozerG/WinYandexMusicRPC/assets/175156157/8f6e0f9b-5ec3-481e-abf3-c6a35115c5b4)

OS: Windows 10 22H2

**Comment by Jushara** [comment]
Убрать из свойств exe файла запуск от имени администратора

**Comment by FozerG** [comment]
> Убрать из свойств exe файла запуск от имени администратора

Уточнение: речь идет о Discord.
