### ISSUE TITLE
Медленная скорость скачивания файла с github

### ISSUE THREAD

**Issue by Mihail-pesov** [FozerG/WinYandexMusicRPC#46]
Я Столкнулся с проблемой: Оооочень долго качает .exe это больше приколы git hub так по мне лучше закинуть exe в заархивированный архив так будет быстрее.
Что я сделал что бы получить эту проблему: Начал скачивание

Вот скриншот с логами скрипта/проблемой:
![image](https://imgur.com/a/QCUHzkn)

OS: Windows 10 LTSC 21H2 (чистая, не сборка)
-

**Comment by eggdll** [comment]
Скриншот поврежден

**Comment by FozerG** [comment]
У меня скачивание занимает около 30 секунд при скорости ~5 мб/c, что вполне приемлемо. Закрываю тикет, но если у других пользователей возникнут проблемы, пишите сюда :)

![image](https://github.com/user-attachments/assets/e7b5700d-95a5-4cca-8f91-08aabd71c946)
