### ISSUE TITLE
winsdk returned empty string for artist or title

### ISSUE THREAD

**Issue by mozes5596** [FozerG/WinYandexMusicRPC#47]
дс запущен, яндекс музыка тоже. Хз что делать
попробовал войти в акк яндекс, не помогло
(перезагрузил комп и заработало)
![image](https://github.com/user-attachments/assets/2ce41407-8490-4a59-bec8-2bde1ebea1c4)

**Comment by FozerG** [comment]
Иногда помогает комбинация клавиш WIN + L (блокировка экрана для ручного обновления winsdk).
