### ISSUE TITLE
Берутся песни из вк

### ISSUE THREAD

**Issue by ssouthh** [FozerG/WinYandexMusicRPC#48]
Я Столкнулся с проблемой: При включении (либо если осталась в фоне но на паузе) какой либо песни в вк, то она транслируется в discord rpc, при этом игнорируя яндекс музыку
Что я сделал что бы получить эту проблему: Включил песню в Я.М, поставил на паузу, включил песню в вк, поставил песню в вк на паузу

Вот скриншот с логами скрипта/проблемой:
https://youtu.be/glwXC9cWnM8

OS: Windows 10 LTSC 22H2 (чистая, не сборка)
Слушаю музыку через браузер/приложение Я.Музыка: Приложение Я.М

**Comment by FozerG** [comment]
Трудно сказать, почему это происходит. Я попробовал Яндекс Музыку и ВКонтакте в браузере — всё работает нормально. Возможно, приложение Яндекс Музыки имеет более высокий приоритет чем браузер на паузе. В любом случае, при запуске песни в ВКонтакте она снова будет отображаться.

**Comment by ssouthh** [comment]
> Попробуй описать проблему чуть подробнее. Ты пишешь одно, но на видео всё кажется работающим как надо.

Вроде норм описал + на видео видно же. Ну в общем, включаешь музыку из вк, и она есть в яндекс музыке - она транслируется в discord rpc, если этой же песни в яндекс музыке - что-то бесконечно флудит в консоль, конкретно не помню что, но флудит

**Comment by Skiexx** [comment]
Скорее всего текущая песня берется не на основе приложения Yandex Music, а из Windows Media API(Или как там). Поэтому хватает любую абсолютно медиа, а не только из Yandex.

**Comment by FozerG** [comment]
Так и должно работать. Человек выше объяснил принцип работы скрипта.
