### ISSUE TITLE
Vencord Plugin

### ISSUE THREAD

**Issue by Jushara** [FozerG/WinYandexMusicRPC#49]
[Я Столкнулся с проблемой как в тикете #45](https://github.com/FozerG/WinYandexMusicRPC/issues/45)

Подумал, что проблема возможно в том что я использую Vencord, хотя раньше все работало штатно и с более старой версией скрипта которая опубликована не только одним экзешником (сложно понять ошибку по которой он не работает, так же вылетает), обновился на последнюю версию, [не помогло, сыпет ошибки из тикета 45](https://github.com/FozerG/WinYandexMusicRPC/issues/45)

_Возникла такая мысль, возможно ли перенести/интегрировать скрипт в плагины Vencord?_ 

Уже встроен плагин для LastFM, наверняка и для ЯМ можно сделать

https://vencord.dev/plugins

**Comment by FozerG** [comment]
Честно говоря, я и не знал о существовании такого клиента. В тикетах библиотеки, которую я использую для RPC, я нашёл следующее: ["Попробуйте отключить плагины, связанные с RPC, такие как CustomRPC и NoRPC."](https://github.com/developers192/DetailedLoLRPC/issues/15#issuecomment-2173141781). 

Да и я также не уверен, что [поддержка этого клиента](https://github.com/qwertyquerty/pypresence/issues/240) вообще есть. 

А версия [1.9.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9.1) работает? Там устаревшая проверка доступности Discord.

**Comment by Jushara** [comment]
> Честно говоря, я и не знал о существовании такого клиента. В тикетах библиотеки, которую я использую для RPC, я нашёл следующее: ["Попробуйте отключить плагины, связанные с RPC, такие как CustomRPC и NoRPC."](https://github.com/developers192/DetailedLoLRPC/issues/15#issuecomment-2173141781).
> 
> Да и я также не уверен, что [поддержка этого клиента](https://github.com/qwertyquerty/pypresence/issues/240) вообще есть.
> 
> А версия [1.9.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9.1) работает? Там устаревшая проверка доступности Discord.

Все оказалось намного проще, ответил в первоначальной теме, что дискорд не следуют запускать от имени администратора (требовалось когда режим рации не работал в играх, которые запускаются таким образом) и все в полном порядке.
