### ISSUE TITLE
Вопрос: можно ли создать такой же плагин для телефона?

### ISSUE THREAD

**Issue by WolfRam1d** [FozerG/WinYandexMusicRPC#51]
Есть ли возможность сделать такой же плагин для телефонов? И есть ли вообще уже такие плагины в интернете?
Был бы рад отображению треков, слушаемых с телефона

**Comment by FozerG** [comment]
Я не слышал о подобных плагинах и сомневаюсь, что такие существуют. Я пробовал получать текущий трек с помощью API Yandex Music, но это работает не совсем корректно. Возможно, если создать отдельное приложение с использованием [Kizzy](https://github.com/dead8309/Kizzy) и получать текущий трек через [Android MediaSession API](https://developer.android.com/reference/android/media/MediaPlayer), это будет теоретически работать. Однако, это новый для меня стек, и у меня нет планов этим заниматься.
