### ISSUE TITLE
Не идет таймер, если стоит "слушает" 

### ISSUE THREAD

**Issue by Hikurai** [FozerG/WinYandexMusicRPC#52]
Я Столкнулся с проблемой: не идет таймер, если стоит активность "слушает" как будто бы музыка стоит на паузе. При "играет" подобного нет. 

Вот скриншот с логами скрипта/проблемой:
https://i.imgur.com/KIggTFC.png

OS: Windows 11 23H2
Слушаю музыку через приложение: Яндекс Музыка

----

Еще такой "пук" в воздух. Если запущен GoodbieDPI, то окно с авторизацией не прогружается. Не критично вообще, но все равно скажу раз пишу :/

**Comment by FozerG** [comment]
Для активности "Слушает" невозможно добавить таймер. Надеемся, что в будущем Discord добавит поддержку временной шкалы.
