### ISSUE TITLE
Неправильное отображение статуса при выборе "слушает"

### ISSUE THREAD

**Issue by OwlAndDot** [FozerG/WinYandexMusicRPC#53]
При выборе "слушает" для других пользователей неправильно отображается, т.е. как вижу я:
https://imgur.com/6uS1TcH
Как видят другие:
https://imgur.com/Ldacf00

При этом при выбора статуса в настройках "играет" отображается все правильно.
В логах ничего нет, кроме инфы об играющих треках.

OS: Windows 10  22H2 пираченная
Слушаю музыку через приложение Я.Музыка

**Comment by FozerG** [comment]
> При выборе "слушает" для других пользователей неправильно отображается, т.е. как вижу я: https://imgur.com/6uS1TcH Как видят другие: https://imgur.com/Ldacf00
> 
> При этом при выбора статуса в настройках "играет" отображается все правильно. В логах ничего нет, кроме инфы об играющих треках.
> 
> OS: Windows 10 22H2 пираченная Слушаю музыку через приложение Я.Музыка

А у других последняя версия дискорда? Попробуй проверить свой статус через веб-версию Discord, потому что я тестировал именно таким образом.

**Comment by FozerG** [comment]
Скорее всего, это совершенно другой Discord RPC. Открой вкладку "Активность" в своём профиле.

**Comment by OwlAndDot** [comment]
Тут полностью моя оплошность была - яндекс музыка засунулась в активность в дискорде, т.е. был конфликт между приложением яндекс музыки и Вашим приложением.
После удаления её оттуда все заработало правильно.
