### ISSUE TITLE
Проблема со скриптом: не отображается трек 4'33'' — John Cage

### ISSUE THREAD

**Issue by Valeron-bit** [FozerG/WinYandexMusicRPC#54]
Я столкнулся с проблемой: Скрипт не хочет отображать в статусе трек 4'33'' - John Cage.
Что я сделал что бы получить эту проблему: включил трек.

Вот скриншот с логами скрипта/проблемой:
![image](https://github.com/user-attachments/assets/a20630be-1fd5-44c9-a40f-6706876b7eb8)
![image](https://github.com/user-attachments/assets/b5bbad3d-eb24-471b-8e73-9b827cbeb6cb)

OS: Windows 11 Pro 22H2 (чистая, не сборка)
Слушаю музыку через приложение Я.Музыка

**Comment by WolfRam1d** [comment]
Аналогичная проблема была с другим треком около суток назад.

**Comment by FozerG** [comment]
Проблема связана с поиском яндекса: по какой то причине он не обрабатывает спец.символы, такие как двойные кавычки, и не возвращает трек по полному названию. Я попробую исправить это, когда появится время.

**Comment by Valeron-bit** [comment]
> Проблема связана с поиском яндекса: по какой то причине он не обрабатывает спец.символы, такие как двойные кавычки, и не возвращает трек по полному названию. Я попробую исправить это, когда появится время.

 А такие символы обрабатывает почему-то
 
![image](https://github.com/user-attachments/assets/d5d72dae-4356-4c45-a06a-40b11ba27084)

**Comment by FozerG** [comment]
> > Проблема связана с поиском яндекса: по какой то причине он не обрабатывает спец.символы, такие как двойные кавычки, и не возвращает трек по полному названию. Я попробую исправить это, когда появится время.
> 
> А такие символы обрабатывает почему-то
> 
> ![image](https://private-user-images.githubusercontent.com/70327872/358521463-d5d72dae-4356-4c45-a06a-40b11ba27084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDg0MjMsIm5iZiI6MTcyMzgwODEyMywicGF0aCI6Ii83MDMyNzg3Mi8zNTg1MjE0NjMtZDVkNzJkYWUtNDM1Ni00YzQ1LWEwNmEtNDBiMTFiYTI3MDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzA0NWM2MGMyMzY0MWU2MTdmMjFjNzA3YmQ5ZmMzZmY3OTI1ZjlkMzYxODE0MGYyOTI4MDJhOGQ4NGNmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oAVKBzR5wrPbDmBEEIU7J_r9QUikLUQ8vZ6oSsPKrdM)

Поиск Яндекса работает очень непредсказуемо. Можно проверить это самому [здесь](https://music.yandex.ru/search?text=4%2733%27%27%20john%20cage%20). Но стоит убрать специальные символы, и песня сразу находится.

**Comment by Valeron-bit** [comment]
> > > Проблема связана с поиском яндекса: по какой то причине он не обрабатывает спец.символы, такие как двойные кавычки, и не возвращает трек по полному названию. Я попробую исправить это, когда появится время.
> > 
> > 
> > А такие символы обрабатывает почему-то
> > ![image](https://private-user-images.githubusercontent.com/70327872/358521463-d5d72dae-4356-4c45-a06a-40b11ba27084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDg0MjMsIm5iZiI6MTcyMzgwODEyMywicGF0aCI6Ii83MDMyNzg3Mi8zNTg1MjE0NjMtZDVkNzJkYWUtNDM1Ni00YzQ1LWEwNmEtNDBiMTFiYTI3MDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzA0NWM2MGMyMzY0MWU2MTdmMjFjNzA3YmQ5ZmMzZmY3OTI1ZjlkMzYxODE0MGYyOTI4MDJhOGQ4NGNmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oAVKBzR5wrPbDmBEEIU7J_r9QUikLUQ8vZ6oSsPKrdM)
> 
> Поиск Яндекса работает очень непредсказуемо. Можно проверить это самому [здесь](https://music.yandex.ru/search?text=4%2733%27%27%20john%20cage%20). Но стоит убрать специальные символы, и песня сразу находится.

Почему в приложении отображаться одна обложка и в статусе совсем другая?

**Comment by FozerG** [comment]
> > > > Проблема связана с поиском яндекса: по какой то причине он не обрабатывает спец.символы, такие как двойные кавычки, и не возвращает трек по полному названию. Я попробую исправить это, когда появится время.
> > > 
> > > 
> > > А такие символы обрабатывает почему-то
> > > ![image](https://private-user-images.githubusercontent.com/70327872/358521463-d5d72dae-4356-4c45-a06a-40b11ba27084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDg0MjMsIm5iZiI6MTcyMzgwODEyMywicGF0aCI6Ii83MDMyNzg3Mi8zNTg1MjE0NjMtZDVkNzJkYWUtNDM1Ni00YzQ1LWEwNmEtNDBiMTFiYTI3MDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExMzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzA0NWM2MGMyMzY0MWU2MTdmMjFjNzA3YmQ5ZmMzZmY3OTI1ZjlkMzYxODE0MGYyOTI4MDJhOGQ4NGNmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oAVKBzR5wrPbDmBEEIU7J_r9QUikLUQ8vZ6oSsPKrdM)
> > 
> > 
> > Поиск Яндекса работает очень непредсказуемо. Можно проверить это самому [здесь](https://music.yandex.ru/search?text=4%2733%27%27%20john%20cage%20). Но стоит убрать специальные символы, и песня сразу находится.
> 
> Почему в приложении отображаться одна обложка и в статусе совсем другая?

Такое бывает, когда у исполнителя один и тот же трек сначала выпускается как сингл, а позже включается в альбом.
Пример:
![image](https://github.com/user-attachments/assets/60237a64-4130-4c12-a560-137a29811fbf)

**Comment by lenorio** [comment]
Скрипт распознает " как конец ввода, не определив автора пытается снова найти, у него не получается и после 3 попыток его рейтблочит

**Comment by FozerG** [comment]
https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.3

**Comment by FozerG** [comment]
Исправлено в [релизе 2.3](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.3)
