### ISSUE TITLE
venv

### ISSUE THREAD

**Issue by nikitairl** [FozerG/WinYandexMusicRPC#55]
Readme говорит об установке зависимостей без создания виртуального окружения. 
Хочу порекомендовать дополнить доку следующей командой:
```shell
python -m venv venv #для создания виртуального окружения
.\venv\Scripts\activate #для активации виртуального окружения
```
После чего уже можно устанавливать зависимости и компилировать .exe.

Спасибо за рассмотрение и потраченное время.

**Comment by FozerG** [comment]
Readme рассчитан для новичков в python, и добавление виртуального окружения может создать для них неудобства. Я думаю те кому нужна изоляция, смогут самостоятельно создать виртуальное окружение. Спасибо за предложение.
