### ISSUE TITLE
Не показывает трек

### ISSUE THREAD

**Issue by WolfRam1d** [FozerG/WinYandexMusicRPC#56]
Я Столкнулся с проблемой: не показывается трек

Вот скриншот с логами скрипта/проблемой:
![image](https://github.com/user-attachments/assets/57883f8d-9906-4739-8ed3-e138c8f091fc)

OS: Windows 10 Home 22H2 (чистая, не сборка)
Слушаю музыку через приложение Я.Музыка

**Comment by FozerG** [comment]
Используешь обычную версию Discord? Пробовал перезапускать его?

**Comment by WolfRam1d** [comment]
> Используешь обычную версию Discord? Пробовал перезапускать его?

Да, обычный дискорд. Перезапускал несколько раз

**Comment by FozerG** [comment]
Мало могу помочь с этой проблемой, так как она на стороне библиотеки pypresence, но попробуй открыть PowerShell и ввести туда `Get-ChildItem -Path \\.\pipe\ | Where-Object { $_.Name -like "*discord-ipc*" }`. Отправь результат.

**Comment by WolfRam1d** [comment]
![image](https://github.com/user-attachments/assets/045b1def-1d36-4166-a811-5fd2306949b4)

**Comment by FozerG** [comment]
Попробуй запускать скрипт от имени администратора или другую версию например [1.9.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v1.9.1)

**Comment by WolfRam1d** [comment]
Скрипит был починен перезапуском
