### ISSUE TITLE
Нагрузка на процессор

### ISSUE THREAD

**Issue by SPIDEGames** [FozerG/WinYandexMusicRPC#57]
Я столкнулся с проблемой: 100-процентная нагрузка на процессор.
Что я сделал, чтобы получить эту проблему: переключил трек, иногда само по себе (редко появляется).

Вот скриншот с логами скрипта/проблемой:
Не успел заскринить, проц на сотку нагружен, даже диспетчер зависает, а когда отвисает, ничего уже нету, консоль пустая. Попробую поймать момент, залью в комменты.
Один из процессов, который нагружает:
![image](https://github.com/user-attachments/assets/f8c99337-c2ea-4491-83c1-58bd0b159946)

OS: Windows 11 Pro (чистая, не сборка).
Слушаю музыку через браузер/приложение «Я.Музыка»: новое приложение Яндекс Музыки.

**Comment by FozerG** [comment]
Как указано [здесь](https://answers.microsoft.com/en-us/windows/forum/all/service-host-npsmsvc1f1c1b99-using-99-cpu-usage/c15d6a26-de12-4c3f-b03a-5c02174f3603), данный процесс отвечает за передачу медиа в Windows.Media.Control API. Остается под вопросом, как нагрузка на этот процесс связана со скриптом, поскольку это может делать и приложение Яндекс.Музыки.

**Comment by hikimeru** [comment]
при смене песен идет нагрузка на вот эти штучки
![image](https://github.com/user-attachments/assets/f99233d3-e00a-44ad-b5b4-b0ec3cc69156)

**Comment by hikimeru** [comment]
В прошлой версии потребление в районе 10 процентов, а еще в более прошлых - 2-3 процента.

**Comment by toshundris1** [comment]
тоже поднимал подобную проблему, но отмечусь и здесь, так как если проблема раньше появлялась редко но метко, то сейчас каждый день приходится при нагрузке процессора выключать rpc, как бы этого ни хотелось делать =(

**Comment by SPIDEGames** [comment]
> Как указано [здесь](https://answers.microsoft.com/en-us/windows/forum/all/service-host-npsmsvc1f1c1b99-using-99-cpu-usage/c15d6a26-de12-4c3f-b03a-5c02174f3603), данный процесс отвечает за передачу медиа в Windows.Media.Control API. Остается под вопросом, как нагрузка на этот процесс связана со скриптом, поскольку это может делать и приложение Яндекс.Музыки.

Почему тогда когда не запущен rpc этот процесс молчит, не нагружает, сколько не смотрел. Даже на 2-ой монитор выводил диспетчер, ни разу он так не нагружал ЦП

**Comment by saintedlittle** [comment]
> > Как указано [здесь](https://answers.microsoft.com/en-us/windows/forum/all/service-host-npsmsvc1f1c1b99-using-99-cpu-usage/c15d6a26-de12-4c3f-b03a-5c02174f3603), данный процесс отвечает за передачу медиа в Windows.Media.Control API. Остается под вопросом, как нагрузка на этот процесс связана со скриптом, поскольку это может делать и приложение Яндекс.Музыки.
> 
> Почему тогда когда не запущен rpc этот процесс молчит, не нагружает, сколько не смотрел. Даже на 2-ой монитор выводил диспетчер, ни разу он так не нагружал ЦП

Потому-что RPC общается для получения данных с этой службой.

**Comment by FozerG** [comment]
В [релизе 2.3](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.3) я провел максимальную оптимизацию и перешел на новую библиотеку для взаимодействия с Windows.Media.Control. Буду рад, если оставите свои отзывы о новой версии здесь.
