### ISSUE TITLE
не пишет что я слушаю яндекс музыку, пишет что я просто слушаю

### ISSUE THREAD

**Issue by TayXDXDXDXD** [FozerG/WinYandexMusicRPC#58]
проблема на скриншоте
![image](https://github.com/user-attachments/assets/221a079f-0f57-43b6-b422-d59769e8b5ca)

**Comment by Valeron-bit** [comment]
Просто поинтересуюсь, а в чем проблема собственно?

**Comment by FozerG** [comment]
> проблема на скриншоте ![image](https://private-user-images.githubusercontent.com/161330483/358302707-221a079f-0f57-43b6-b422-d59769e8b5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTU4OTIsIm5iZiI6MTcyMzk1NTU5MiwicGF0aCI6Ii8xNjEzMzA0ODMvMzU4MzAyNzA3LTIyMWEwNzlmLTBmNTctNDNiNi1iNDIyLWQ1OTc2OWU4YjVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNDMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDhhNjFkNTkxYmQ3MDMxYjFlN2IyZWJiZDhmYWNhYjdiNzk0OTA3NmJjNjJkMTA0YTE2N2EyYWRmYTNkNzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.grflVOUg8qXNpMU4Qyfnc5qUXNanFy4viT4SVryZryM)

Для других пользователей так же показывается?

**Comment by Valeron-bit** [comment]
> > проблема на скриншоте ![image](https://private-user-images.githubusercontent.com/161330483/358302707-221a079f-0f57-43b6-b422-d59769e8b5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTU4OTIsIm5iZiI6MTcyMzk1NTU5MiwicGF0aCI6Ii8xNjEzMzA0ODMvMzU4MzAyNzA3LTIyMWEwNzlmLTBmNTctNDNiNi1iNDIyLWQ1OTc2OWU4YjVjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNDMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDhhNjFkNTkxYmQ3MDMxYjFlN2IyZWJiZDhmYWNhYjdiNzk0OTA3NmJjNjJkMTA0YTE2N2EyYWRmYTNkNzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.grflVOUg8qXNpMU4Qyfnc5qUXNanFy4viT4SVryZryM)
> 
> Для других пользователей так же показывается?

![image](https://github.com/user-attachments/assets/22551c3b-a06b-4566-bda8-46db50fb1f20)

**Comment by FozerG** [comment]
На первом скриншоте у тебя язык RPC на русском, а на другом на английском, но это не суть. Как видно, для других пользователей всё отображается корректно. В последнее время Discord работает странно и может некорректно отображать RPC в своем аккаунте.
