### ISSUE TITLE
Для чего нужна возможность логинится

### ISSUE THREAD

**Issue by FroggerHH** [FozerG/WinYandexMusicRPC#59]
Я увидел кнопку Yandex Settings -> Login to account
Интересно для чего нужна возможность логинится?

OS: Windows 10 LTSC 21H2 (чистая, не сборка)
Слушаю музыку через приложение Я.Музыка

**Comment by FozerG** [comment]
![image](https://github.com/user-attachments/assets/4c11047d-7795-49c5-b911-2c95a6395463)
