### ISSUE TITLE
Winsdk returned empty... FIXED

### ISSUE THREAD

**Issue by WorldXP** [FozerG/WinYandexMusicRPC#62]
![image](https://github.com/user-attachments/assets/d142cd88-0bbd-4eee-a67c-cbf22ad9b582)

ты меня обманываешь

**Comment by FozerG** [comment]
Попробуй перевести компьютер в режим блокировки или перезапустить его

**Comment by WorldXP** [comment]
ребят. фиксится закрытием любого другого источника звука!

**Comment by WorldXP** [comment]
оставь это открытым тут для тех, кто не сильно в гитхабе шарит
