### ISSUE TITLE
Can't find music Sati Akura - USSEWA

### ISSUE THREAD

**Issue by tomioka26** [FozerG/WinYandexMusicRPC#63]
OC : windows 11
![Снимок экрана 2024-09-09 201147]
(https://github.com/user-attachments/assets/9a77a57a-2a76-4c1e-9970-7ae4338e962d)

**Comment by Kisa-rep** [comment]
такая же хрень

**Comment by FozerG** [comment]
![image](https://github.com/user-attachments/assets/314c0b67-0132-4be9-a8e0-b4cc2a1164f0)


>Зачем мне входить через Яндекс?
Это не обязательно, но рекомендуется в некоторых случаях. Если вы используете скрипт в странах, где недоступна [бесплатная версия Яндекс Музыки](https://ru.wikipedia.org/wiki/%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_%D0%9C%D1%83%D0%B7%D1%8B%D0%BA%D0%B0#:~:text=%D0%9F%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B0%20%D0%BD%D0%B0%20%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%B0%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F%D0%BC%20%D0%B8%D0%B7%20%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D0%B8%D1%85%20%D1%81%D1%82%D1%80%D0%B0%D0%BD%3A%20%D0%90%D0%B7%D0%B5%D1%80%D0%B1%D0%B0%D0%B9%D0%B4%D0%B6%D0%B0%D0%BD%2C%20%D0%90%D1%80%D0%BC%D0%B5%D0%BD%D0%B8%D1%8F%2C%20%D0%91%D0%B5%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%93%D1%80%D1%83%D0%B7%D0%B8%D1%8F%2C%20%D0%98%D0%B7%D1%80%D0%B0%D0%B8%D0%BB%D1%8C%2C%20%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD%2C%20%D0%9A%D1%8B%D1%80%D0%B3%D1%8B%D0%B7%D1%81%D1%82%D0%B0%D0%BD%2C%20%D0%9C%D0%BE%D0%BB%D0%B4%D0%B0%D0%B2%D0%B8%D1%8F%2C%20%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%2C%20%D0%A2%D0%B0%D0%B4%D0%B6%D0%B8%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD%2C%20%D0%A2%D1%83%D1%80%D0%BA%D0%BC%D0%B5%D0%BD%D0%B8%D1%81%D1%82%D0%B0%D0%BD%2C%20%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD%5B48%5D.), или используете VPN. Вход через Яндекс может помочь избежать ошибок. Кроме того, авторизация через Яндекс позволяет получить доступ к трекам, которые недоступны без входа в систему. Если у вас нет подписки "Плюс", вход будет скорее безполезным.
