### ISSUE TITLE
Программа видит Discord, но не ставит статус. 

### ISSUE THREAD

**Issue by timpo14** [FozerG/WinYandexMusicRPC#64]
Я Столкнулся с проблемой: программа видит Discord, но не ставит статус. 
Что я сделал что бы получить эту проблему: Просто запустил WinYandexMusicRPC, лол.

Вот скриншот с логами скрипта/проблемой:
![image](https://github.com/user-attachments/assets/668b0ac4-030e-40ab-9802-412e0b93f8e6)

OS: Windows 10 Pro 22H2 (чистая, не сборка)
Слушаю музыку через приложение Я.Музыка

**Comment by FozerG** [comment]
Трудно сказать, установленая обычная версия Discord? Перезапуск не помог?

**Comment by Flakoooo** [comment]
Была такая же ошибка
У меня Discord запускается от имени администратора, я запустил скрипт от имени администратора и помогло

**Comment by timpo14** [comment]
> Трудно сказать, установленая обычная версия Discord? Перезапуск не помог?

Про Discord трудно сказать, binary/canary если не ошибаюсь
Перезапуск не помог

**Comment by timpo14** [comment]
> Была такая же ошибка У меня Discord запускается от имени администратора, я запустил скрипт от имени администратора и помогло
Попробовал ,не помогает
Ща v2.3 качать буду

**Comment by FozerG** [comment]
> > Трудно сказать, установленая обычная версия Discord? Перезапуск не помог?
> 
> Про Discord трудно сказать, binary/canary если не ошибаюсь Перезапуск не помог

Почему...

Используй обычную версию
