### ISSUE TITLE
После запуска трека зависает комп с помехами в звуке

### ISSUE THREAD

**Issue by IScreamOI** [FozerG/WinYandexMusicRPC#65]
Столкнулся с проблемой, что после включения этого трека, начинает фонить звук и фризить пк. 
![image](https://github.com/user-attachments/assets/eb0aec3c-cdec-44a8-abc2-04d1b9a083e8)
Скорее всего, это из-за того, что слишком много авторов (так и есть).
Слушаю с приложения, Win 11 pro 24h2

**Comment by FozerG** [comment]
Проблема есть, будет исправлено! Спасибо!

**Comment by FozerG** [comment]
Исправлено в [релизе 2.3](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.3)
