### ISSUE TITLE
the music is not playing right now

### ISSUE THREAD

**Issue by scream-dev** [FozerG/WinYandexMusicRPC#66]
![image](https://github.com/user-attachments/assets/9c845f31-9d9f-4923-b634-461bbe06d593)
Я вошёл в аккаунт, включил музыку, но нету ничего в дискорде

**Comment by TayXDXDXDXD** [comment]
попробуй через приложение включить музыку

**Comment by FozerG** [comment]
Шаблон для Issues создан не просто так. Укажи версию Windows, которой пользуешься, а также какой браузер используешь. Не урезаная Windows, с официального сайта Microsoft?
