### ISSUE TITLE
помогите решить проблему

### ISSUE THREAD

**Issue by MorphyX228** [FozerG/WinYandexMusicRPC#67]
Я Столкнулся с проблемой: при скачивании крипта для отображения яндекс музыки в дискорде , он у меня открывается в командной строке
Что я сделал что бы получить эту проблему: скачал крипт и делал все по инструкции

Вот скриншот с логами скрипта/проблемой:
https://imgur.com/a/ihqLGRd

OS: Windows 11
Слушаю музыку через браузер

**Comment by TayXDXDXDXD** [comment]
а что не так? он же должен открываться в командной строке

**Comment by FozerG** [comment]
![image](https://github.com/user-attachments/assets/32368e82-d198-49ad-ba54-7bc42774447d)
