### ISSUE TITLE
winsdk returned empty string for artist or title

### ISSUE THREAD

**Issue by buzzblader** [FozerG/WinYandexMusicRPC#68]
Я Столкнулся с проблемой: показано на скриншоте (winsdk returned empty string for artist or title)
Что я сделал что бы получить эту проблему: запустил с имени/без администратора

Вот скриншот с логами скрипта/проблемой:
![image](https://github.com/user-attachments/assets/387a364c-588d-4a8d-b855-8daae0f4b575)

OS: Windows 11 Pro 23H2 (чистая, не сборка)
Слушаю музыку приложение Я.Музыка

**Comment by FozerG** [comment]
Иногда помогает комбинация клавиш WIN + L (блокировка экрана для ручного обновления winsdk).
Иногда помогает закрытие приложений которые воспроизводят звук.
Иногда помогает перезапуск приложения яндекс музыки или браузера,
Иногда помогает перезапуск ПК.
