### ISSUE TITLE
python main.py

### ISSUE THREAD

**Issue by iv4n999** [FozerG/WinYandexMusicRPC#69]
делая компил через Pyinstaller ошибка 18 и 2 линии что делать? 
хотел сделать для прослуш вк из бразуера
![powershell_VKU4tOd04A](https://github.com/user-attachments/assets/41e52866-3100-4f2e-b287-82b25cf6fa59)

**Comment by FozerG** [comment]
pip install -r requirements.txt / pip install

**Comment by iv4n999** [comment]
я делал инстал
