### ISSUE TITLE
cmd не является внутренней или внешней командой исполняемой программой или пакетным файлом

### ISSUE THREAD

**Issue by MineGamesYT** [FozerG/WinYandexMusicRPC#70]
При открытии exe файла в консоли программы выскакивает такая ошибка:  "cmd - не является внутренней или внешней командой, исполняемой программой или пакетным файлом. Wait a few seconds for the script to load...

![Снимок экрана 2024-10-05 084841](https://github.com/user-attachments/assets/2b1ac708-2b26-4b88-8f9f-97f03a5a3662)

помогите разобраться с проблемой. в интернете ответа не нашел...

**Comment by iv4n999** [comment]
пробовал от админа?

**Comment by MineGamesYT** [comment]
Да, пробовал запускать от админа - результат тот же

**Comment by iv4n999** [comment]
у меня такие были такие проблы когда вырус цепал и с cmd были проблемы

**Comment by FozerG** [comment]
C:\Windows\System32 -> cmd.exe существует? Windows с оффицального сайта майкрософт? 

Как костыль можно запустить скрипт от сюда -> %temp%/WinYandexMusicRPC

**Comment by FozerG** [comment]
> 1. по пути C:\Windows\System32 существует cmd.exe
> 2. запуская файл по пути %temp%/WinYandexMusicRPC та же самая ошибка...
> 3. виндовс с официального сайта
> 
> интересная проблема. потому что старые версии winyandexmusicRPC запускаются а новые нет.

Покажи скриншот при запуске с "%temp%/WinYandexMusicRPC". Этого не должно быть

**Comment by MineGamesYT** [comment]
> Покажи скриншот при запуске с "%temp%/WinYandexMusicRPC". Этого не должно быть



https://github.com/user-attachments/assets/0603bada-7bee-42ad-a72d-1999ac2baad5

https://github.com/user-attachments/assets/c25a4366-92d1-4795-8384-4470510d8797

![image](https://github.com/user-attachments/assets/0dcce6aa-03ea-4698-afaf-24e2c61cde8d)

**Comment by FozerG** [comment]
Я имею в виду не ручное перетаскивание скачанного файла в temp'. После запуска скрипта должна автоматически создаваться папка 'WinYandexMusicRPC' в temp, где будет находиться распакованный скрипт.

**Comment by MineGamesYT** [comment]
Вау. Спасибо за помощь! все заработало) я запустил его с папки temp. только походу смысла пока что нет уже. так как дискорд помер)) можно закрывать вопрос! спасибо за помощь!
