### ISSUE TITLE
Указанная служба не может быть запущена, так как отключена либо она сама, либо все связанные с ней устройства

### ISSUE THREAD

**Issue by VLAADOS1** [FozerG/WinYandexMusicRPC#71]
В общем то, не ясно что за служба
![image](https://github.com/user-attachments/assets/0059f39c-a7b8-4347-9dae-7299868a4feb)

**Comment by VLAADOS1** [comment]
![image](https://github.com/user-attachments/assets/83caacf1-275d-4e6b-a617-6012ee642cd7)
Вот все отключённые службы, вроде не должно влиять

**Comment by VLAADOS1** [comment]
Как я понял проблема в `MediaManager.request_async()`, по чему то он не может получить список текущих сесий

**Comment by FozerG** [comment]
Службу, используемую скриптом, нельзя включить или отключить через стандартный список служб Windows. Однако она может зависеть от других служб, которые не рекомендуется отключать, таких как "Аудио Windows", "Multimedia Class Scheduler", "Remote Procedure Call (RPC)" и другие. Эта(эти) служба может отсутствовать, если Windows была загружена с источника, где системные компоненты были вырезаны.

**Comment by VLAADOS1** [comment]
Да, как оказалось проблема действительно в NPSMSvc, не понятно правда почему, но и ладно
