### ISSUE TITLE
Поддержка Vesktop

### ISSUE THREAD

**Issue by ggfhgrehytht** [FozerG/WinYandexMusicRPC#72]
Я столкнулся с проблемой: WinYandexMusicRPC не поддерживает Vesktop. Я хочу запросить добавление поддержки для Vesktop.

Что я сделал, чтобы получить эту проблему:
- Установил Vesktop с поддержкой RPC.
- Запустил Я. Музыку и WinYandexMusicRPC 

OS: Windows 10 LTSC 1809 (чистая, не сборка).
Слушаю музыку через браузер/приложение «Я.Музыка»: новое приложение Яндекс Музыки.

**Comment by FozerG** [comment]
Я не тестировал это лично, но по словам @Geardung, это уже реализовано в [версии 2.4](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.4)
