### ISSUE TITLE
winsdk returned empty string

### ISSUE THREAD

**Issue by youtkey** [FozerG/WinYandexMusicRPC#75]
Я Столкнулся с проблемой: не воркает на десятке
Что я сделал что бы получить эту проблему: скачал поставил усе

Вот скриншот с логами скрипта/проблемой:
![изображение](https://github.com/user-attachments/assets/8b4d555c-08b9-42a8-a7b6-e27da0282782)

OS: Windows 10 LTSC 21H2 (чистая, не сборка)
Слушаю музыку через приложение Я.Музыка

**Comment by Geardung** [comment]
https://github.com/FozerG/WinYandexMusicRPC/issues/68#issuecomment-2398575012

> Иногда помогает комбинация клавиш WIN + L (блокировка экрана для ручного обновления winsdk).
> Иногда помогает закрытие приложений которые воспроизводят звук.
> Иногда помогает перезапуск приложения Яндекс Музыки или браузера,
> Иногда помогает перезапуск ПК.

Интересно, есть ли возможность обновить winsdk через скрипт?

**Comment by FozerG** [comment]
> изредка трек ловится ![изображение](https://private-user-images.githubusercontent.com/114859135/381176750-f5a7665d-828f-4766-b8a5-6a391e670514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjQ5MDEsIm5iZiI6MTczMDI2NDYwMSwicGF0aCI6Ii8xMTQ4NTkxMzUvMzgxMTc2NzUwLWY1YTc2NjVkLTgyOGYtNDc2Ni1iOGE1LTZhMzkxZTY3MDUxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNTAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzk2MWM1Y2ViYzE3MWZiODRhYWEyYTBlODg1YmI4MDM5NWIyZTlkZTM2M2M5NGY4YTNkMWRhMWMwOWY5OGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kdLDdb1KQVMnCkFddTEB-OzLvagTLmviaLgqtm0W_N4)

В теории, проблема может быть связана с тем, что Windows не может определить активную медиа-сессию. [Попробуй эту версию](https://drive.google.com/file/d/1sblUish8_XRH2qy9-37V3cup_Hf-JBbn/view?usp=drive_link): в ней мы вручную перебираем активные медиа-сессии и выбираем активную.

**Comment by FozerG** [comment]
> [#68 (comment)](https://github.com/FozerG/WinYandexMusicRPC/issues/68#issuecomment-2398575012)
> 
> > Иногда помогает комбинация клавиш WIN + L (блокировка экрана для ручного обновления winsdk).
> > Иногда помогает закрытие приложений которые воспроизводят звук.
> > Иногда помогает перезапуск приложения Яндекс Музыки или браузера,
> > Иногда помогает перезапуск ПК.
> 
> Интересно, есть ли возможность обновить winsdk через скрипт?

Сложно сказать, за год эта проблема возникала у меня не более пяти раз, и из за этого нет возможности тестирования.

**Comment by saintedlittle** [comment]
У тебя сборка Windows корпоративная. (LTSC). 
Всегда в корпоративной версии были проблемы с сервисами.
