### ISSUE TITLE
Музыка не показывается

### ISSUE THREAD

**Issue by ProexMMm** [FozerG/WinYandexMusicRPC#76]
Я Столкнулся с проблемой: Другим музыка не показывается если включена какая-нибудь другая игра.
Что я сделал что бы получить эту проблему: 
Просто загрузил этот скрипт

Вот скриншот с логами скрипта/проблемой:
![browser_VkXH0PXgTu](https://github.com/user-attachments/assets/6e411a7b-2a49-4fc3-a87c-27b899788b36)

OS: Windows 11 pro 23H2 
Слушаю музыку через приложение Я.Музыка. хз, просто скачал с Microsoft Store. Проверил на последней версии с оф. сайта. Также не работает

**Comment by Geardung** [comment]
Привет, если я правильно понимаю, то на этом экране показывается только одна активность. Посмотри, пожалуйста, в разделе «Активность», которую я отметил стрелочкой на скриншоте. 

> ![Снимок экрана 2024-10-29 232607](https://github.com/user-attachments/assets/661a9f74-2395-48fb-8a02-381c4ca689fd)

**Comment by FozerG** [comment]
Discord устанавливает активный статус для последнего запущенного приложения (или по непонятной логике, которую трудно понять). Поэтому, чтобы статус с музыкой отображался корректно, лучше не запускать другие RPC. И да, как уже упоминалось выше, музыка отображается во вкладке "Активность".
