### ISSUE TITLE
Добавить чтобы таймер был при наведении на канал, как у Spotify

### ISSUE THREAD

**Issue by Workezy** [FozerG/WinYandexMusicRPC#77]
Добавить чтобы таймер был при наведении на канал, как у Spotify
![image](https://github.com/user-attachments/assets/93a0a83e-e3b5-4b0f-91c1-a81bf254bf77)
![image](https://github.com/user-attachments/assets/95b86941-1ecf-4c3a-bee0-8d1f6cce9e43)

**Comment by FozerG** [comment]
Discord не предоставляет такую функцию – он сам решает, показывать таймер или нет. Возможно, это будет добавлено в будущем.
