### ISSUE TITLE
скрипт не отвечает/не работает после запуска

### ISSUE THREAD

**Issue by Karicee** [FozerG/WinYandexMusicRPC#79]
Я Столкнулся с проблемой: в шапке
Что я сделал что бы получить эту проблему: запустил прогу ¯\_(ツ)_/¯

Вот скриншот с логами скрипта/проблемой:
![image](https://github.com/user-attachments/assets/bd2a1972-98dd-45f3-8b51-1d4609f6098a)
)

OS: Windows 11 pro 23H2 чистая
Слушаю музыку через приложение Я.Музыка (бетка)

**Comment by FozerG** [comment]
Yandex Settings -> Login to account -> Не входить и перезапустить скрипт.

**Comment by Karicee** [comment]
![image](https://github.com/user-attachments/assets/fe72ea3b-c64d-4635-a2ae-1d3b8c2fb804)
всё равно, ничего не происходит после

**Comment by FozerG** [comment]
[Попробуй эту версию](https://drive.google.com/file/d/1sblUish8_XRH2qy9-37V3cup_Hf-JBbn/view?usp=drive_link)

**Comment by Karicee** [comment]
не помогло, аналогичная ситуация как на скрине выше

**Comment by FozerG** [comment]
![image](https://github.com/user-attachments/assets/268298da-af29-4043-87d0-6d49b4ebcdde)
Если сюда нажать, есть Яндекс Музыка как у меня?

**Comment by Karicee** [comment]
неа. хоткеи для медиа на я.музыку тоже не действуют

**Comment by FozerG** [comment]
С браузером тоже самое?

**Comment by snayz13** [comment]
Та же ошибка( 
Браузер - не работает
Оба приложения - не работают
Впн - тоже мимо
Логинился через аккаунт - всё равно молчит
Ошибок никаких нету, как будто rpc не видит яндекса(

**Comment by FozerG** [comment]
> Та же ошибка( Браузер - не работает Оба приложения - не работают Впн - тоже мимо Логинился через аккаунт - всё равно молчит Ошибок никаких нету, как будто rpc не видит яндекса(

В панели Windows как на скрине выше, есть музыка?

**Comment by snayz13** [comment]
> > Та же ошибка( Браузер - не работает Оба приложения - не работают Впн - тоже мимо Логинился через аккаунт - всё равно молчит Ошибок никаких нету, как будто rpc не видит яндекса(
> 
> В панели Windows как на скрине выше, есть музыка?

нет, в панели нету(
![photo_2024-11-18_14-34-04](https://github.com/user-attachments/assets/3cf3c1a9-4cfe-4bb5-ac2c-017870c1176c)

**Comment by FozerG** [comment]
Единственное чем я могу помочь - https://www.partitionwizard.com/partitionmanager/windows-11-action-center-wont-open.html
