### ISSUE TITLE
Несколько багов

### ISSUE THREAD

**Issue by KOTOKOPOLb** [FozerG/WinYandexMusicRPC#8]
Статус отображается только на клиенте, у других не показывается
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/82699565/6854b375-d39b-4ede-bdc3-385376c8547d)
Возможно проблема именно у меня, но точно сказать не могу.

**Comment by KOTOKOPOLb** [comment]
+ иногда не хочет ставить название
```
[WinYandexMusicRPC] -> Launched. Check the actual version...
[WinYandexMusicRPC] -> You are using the latest version of the script
Yandex Music API v2.1.1, Copyright (C) 2019-2023 Ilya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

[WinYandexMusicRPC] -> Now listening to КИНО - Закрой за мной дверь
[WinYandexMusicRPC] -> Cant find the song (strong_find). Now play: КИНО - Закрой за мной дверь. But we find: КИНО - Закрой за мной дверь, я ухожу
[WinYandexMusicRPC] -> Clear RPC
[WinYandexMusicRPC] -> Clear RPC
```

**Comment by KOTOKOPOLb** [comment]
нашёл ещё пару багов, их тут описать или создать другой запрос?

**Comment by KOTOKOPOLb** [comment]
Windows стал блокировать новую версию (1.5)
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/82699565/1501afec-ea34-40dc-8253-6202e2dbff49)

**Comment by KOTOKOPOLb** [comment]
После паузы или перемотки трека время отображается не правильно
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/82699565/29f2e5e2-55da-493b-afef-f6f39244a4eb)

**Comment by FozerG** [comment]
> После паузы или перемотки трека время отображается не правильно ![image](https://private-user-images.githubusercontent.com/82699565/310594359-29f2e5e2-55da-493b-afef-f6f39244a4eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTQzNTktMjlmMmU1ZTItNTVkYS00OTNiLWFmZWYtZjZmMzkyNDRhNGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjZmNjRlODBkMGFlZDcwZTJjYTQ1M2M5ODJjYTkzNzgzNDc4NWJhNThjMWE3NTgxZTJkY2VkYThjZmM1ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o9X4k5jbqWRfC8-YNaoiCpkg8iDpa1-5zo-_HUqf37A)

Восстановление времени после паузы - в планах, но отследить перемотку к сожалению невозможно.

**Comment by FozerG** [comment]
> Windows стал блокировать новую версию (1.5) ![image](https://private-user-images.githubusercontent.com/82699565/310592982-1501afec-ea34-40dc-8253-6202e2dbff49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTI5ODItMTUwMWFmZWMtZWEzNC00MGRjLTgyNTMtNjIwMmUyZGJmZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NTQzNDhlMDA3NTU4MDMwZTAzYjlkOTk2MWU5ZDUxOWJhMGY2ZTgwMWY1NWZmZWM3MjhiOWRlNzlhOGUwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDqHRy25FLTatL-erbD0v3qeTyBbxvkOdsOs4uL2quY) ![image](https://private-user-images.githubusercontent.com/82699565/310593247-500b6c7e-d0ef-40f8-89e1-c528fc429ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTMyNDctNTAwYjZjN2UtZDBlZi00MGY4LTg5ZTEtYzUyOGZjNDI5ZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MmMyNzU1N2FmMzY3NmYzM2NiNjU1MzNmODNiMDFkZWY3NDE3ZWNhN2M0NjEzMmE2NDUyNTRlMWUxZWUyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MxHl00atkf08QqbGwRWc2JGhuqfee2MUZn_WwTCPp9w)

Неприятный момент, но вообще, это нормальная практика, что скомпилированный код Python ошибочно воспринимается антивирусами как вирус. Это решается только либо цифровой подписью файла, что в текущих обстоятельствах не имеет смысла, либо написанием лично каждому антивирусу с просьбой удалить файл из обнаружения. Я попробую что-нибудь сделать и был бы рад, если ты оставил свою почту, чтобы я мог отправить новую версию для тестирования.

**Comment by KOTOKOPOLb** [comment]
> > Windows стал блокировать новую версию (1.5) ![image](https://private-user-images.githubusercontent.com/82699565/310592982-1501afec-ea34-40dc-8253-6202e2dbff49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTI5ODItMTUwMWFmZWMtZWEzNC00MGRjLTgyNTMtNjIwMmUyZGJmZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NTQzNDhlMDA3NTU4MDMwZTAzYjlkOTk2MWU5ZDUxOWJhMGY2ZTgwMWY1NWZmZWM3MjhiOWRlNzlhOGUwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDqHRy25FLTatL-erbD0v3qeTyBbxvkOdsOs4uL2quY) ![image](https://private-user-images.githubusercontent.com/82699565/310593247-500b6c7e-d0ef-40f8-89e1-c528fc429ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTMyNDctNTAwYjZjN2UtZDBlZi00MGY4LTg5ZTEtYzUyOGZjNDI5ZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MmMyNzU1N2FmMzY3NmYzM2NiNjU1MzNmODNiMDFkZWY3NDE3ZWNhN2M0NjEzMmE2NDUyNTRlMWUxZWUyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MxHl00atkf08QqbGwRWc2JGhuqfee2MUZn_WwTCPp9w)
> 
> Неприятный момент, но вообще, это нормальная практика, что скомпилированный код Python ошибочно воспринимается антивирусами как вирус. Это решается только либо цифровой подписью файла, что в текущих обстоятельствах не имеет смысла, либо написанием лично каждому антивирусу с просьбой удалить файл из обнаружения. Я попробую что-нибудь сделать и был бы рад, если ты оставил свою почту, чтобы я мог отправить новую версию для тестирования.

Знаю, сам сталкивался с такой проблемой. Просто на другие версии антивирус не жаловался, а тут - что-то нашёл.

**Comment by FozerG** [comment]
> > > Windows стал блокировать новую версию (1.5) ![image](https://private-user-images.githubusercontent.com/82699565/310592982-1501afec-ea34-40dc-8253-6202e2dbff49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTI5ODItMTUwMWFmZWMtZWEzNC00MGRjLTgyNTMtNjIwMmUyZGJmZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NTQzNDhlMDA3NTU4MDMwZTAzYjlkOTk2MWU5ZDUxOWJhMGY2ZTgwMWY1NWZmZWM3MjhiOWRlNzlhOGUwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDqHRy25FLTatL-erbD0v3qeTyBbxvkOdsOs4uL2quY) ![image](https://private-user-images.githubusercontent.com/82699565/310593247-500b6c7e-d0ef-40f8-89e1-c528fc429ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDY5NzMsIm5iZiI6MTcwOTc0NjY3MywicGF0aCI6Ii84MjY5OTU2NS8zMTA1OTMyNDctNTAwYjZjN2UtZDBlZi00MGY4LTg5ZTEtYzUyOGZjNDI5ZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MmMyNzU1N2FmMzY3NmYzM2NiNjU1MzNmODNiMDFkZWY3NDE3ZWNhN2M0NjEzMmE2NDUyNTRlMWUxZWUyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MxHl00atkf08QqbGwRWc2JGhuqfee2MUZn_WwTCPp9w)
> > 
> > 
> > Неприятный момент, но вообще, это нормальная практика, что скомпилированный код Python ошибочно воспринимается антивирусами как вирус. Это решается только либо цифровой подписью файла, что в текущих обстоятельствах не имеет смысла, либо написанием лично каждому антивирусу с просьбой удалить файл из обнаружения. Я попробую что-нибудь сделать и был бы рад, если ты оставил свою почту, чтобы я мог отправить новую версию для тестирования.
> 
> Знаю, сам сталкивался с такой проблемой на c#. Просто на другие версии антивирус не жаловался, а тут - что-то нашёл. Почта: [polyan444uk@gmail.com](mailto:polyan444uk@gmail.com)

Спасибо. Вышла новая [версия 1.6](https://github.com/FozerG/WinYandexMusicRPC/releases). Пожалуйста, попробуй её и сообщи о результатах.

**Comment by KOTOKOPOLb** [comment]
> Спасибо. Вышла новая [версия 1.6](https://github.com/FozerG/WinYandexMusicRPC/releases). Пожалуйста, попробуй её и сообщи о результатах.

Теперь другие видят статус и трек (который раньше не показывался) отображается, антивирус тоже не стал ругаться на эту версию (1.6).
![image](https://github.com/FozerG/WinYandexMusicRPC/assets/82699565/ed8f1597-2927-43e8-af71-71b3636eda6a)
