### ISSUE TITLE
Выбор приоритетной картинки трека

### ISSUE THREAD

**Issue by srkonst** [FozerG/WinYandexMusicRPC#81]
Предлагаю добавить функцию для выбора приоритетной картинки. Мне кажется лучше, когда фото на треке берётся именно с самого трека, а не с альбома, в который он включён, так как частенько бывает, что у трека в альбоме и у самого альбома разные фотографии. 

![image](https://github.com/user-attachments/assets/4bd860fb-9680-4aee-b87f-11caa4ac6a48)
![image](https://github.com/user-attachments/assets/ef800436-3eb7-48da-962a-22c245263719)
![image](https://github.com/user-attachments/assets/a729f21a-3636-4aeb-8e7e-3e3f32f6d832)

**Comment by FozerG** [comment]
В текущей реализации это невозможно. Выбор обложки полностью зависит от результатов поиска яндекс музыки - отображается та обложка, которая появляется первой в результатах
