### ISSUE TITLE
Фпс дроп при смене песни 

### ISSUE THREAD

**Issue by Avetn** [FozerG/WinYandexMusicRPC#82]
Я Столкнулся с проблемой: потеря кадров при смене песни
Что я сделал что бы получить эту проблему: Врубил скрипт и начал слушать музыку

Вот скриншот с логами скрипта/проблемой:
-

OS: Windows 10 LTSC 21H2 (чистая, не сборка)
Слушаю музыку через браузер/приложение Я.Музыка: Mozilla Firefox 127.0.1 (64-bit)

**Comment by FozerG** [comment]
Проверь есть ли общее с этой проблемой https://github.com/FozerG/WinYandexMusicRPC/issues/57
