### ISSUE TITLE
Could not find QtWebEngineProcess.exe

### ISSUE THREAD

**Issue by RealGuyFromDiscord** [FozerG/WinYandexMusicRPC#83]
Я Столкнулся с проблемой: При попытке залогинится в яндекс, выдаёт эту ошибку.
Что я сделал что бы получить эту проблему: Нажал на "Login to account..."

Вот скриншот с логами скрипта/проблемой:
![image](https://github.com/user-attachments/assets/17fe906e-58fd-476e-ad80-1d5d0b68346b)

OS: Windows 11 (чистая, не сборка)
Слушаю музыку через приложение Я.Музыка

**Comment by FozerG** [comment]
Используешь установочную версию или portable?

**Comment by RealGuyFromDiscord** [comment]
Установочная

**Comment by FozerG** [comment]
Будет это происходить с этой [версией](https://github.com/FozerG/WinYandexMusicRPC/releases/download/v2.3/WinYandexMusicRPC-2-3.exe)?

**Comment by RealGuyFromDiscord** [comment]
Нет, все работает как надо

**Comment by RealGuyFromDiscord** [comment]
![image](https://github.com/user-attachments/assets/ec935fb0-c4f0-4867-b20a-79ccc20a9c8a)

**Comment by FozerG** [comment]
Исправлено в [установочной версии 2.4.1](https://github.com/FozerG/WinYandexMusicRPC/releases/tag/v2.4.1).
При использовании portable-версии рекомендуется избегать кириллицы в пути к скрипту.
