### ISSUE TITLE
The music is not played right now

### ISSUE THREAD

**Issue by xwmedepp** [FozerG/WinYandexMusicRPC#84]
Не работает

OS: Windows 10 pro 22H2 (чистая, не сборка)
Слушаю музыку через браузер/приложение Я.Музыка: next.music.yandex.ru, приложения ям. нигде
![photo_2024-11-23_03-06-05](https://github.com/user-attachments/assets/9b3845e0-5359-481c-ae13-c07038af9471)

**Comment by FozerG** [comment]
Попробуй этот [форк](https://github.com/FozerG/YandexMusicRPC), обязательно прочитай описание.
