### ISSUE TITLE
Ложная пауза

### ISSUE THREAD

**Issue by tumabchic** [FozerG/WinYandexMusicRPC#85]
При включении корректно отображается проигрывание в активности, после в течении 10-15 сек  срабатывает ложная пауза

Вот скриншот с проблемой:
![изображение](https://github.com/user-attachments/assets/53930a66-7c04-451c-b96d-5ff712079a47)

OS: Windows 10 LTSC 21H2 (чистая, не сборка)
Слушаю музыку через приложение (проверял через браузер, проблема дублируется) Я.Музыка: Mozilla Firefox 127.0.1 (64-bit)

**Comment by FozerG** [comment]
Скриншот из с логами из скрипта?

**Comment by tumabchic** [comment]
![изображение](https://github.com/user-attachments/assets/a91489d3-dae6-45fd-a5da-b55f7c6c28f8)
Прога ошибочно ставит трек на паузу(видно в консоли), хотя он играет

**Comment by tumabchic** [comment]
А WinYandexMusicRPC работает корректно?

**Comment by FozerG** [comment]
> А WinYandexMusicRPC работает корректно?

В целом да
