### ISSUE TITLE
нет показа треков с других устройствах, заявленным описанием проекта  

### ISSUE THREAD

**Issue by subwaylover-spb** [FozerG/WinYandexMusicRPC#89]
Я Столкнулся с проблемой:  нет показа треков с других устройств 
цитирую "Этот вариант скрипта не устарел, но возможно вы захотите использовать [эту версию](https://github.com/FozerG/YandexMusicRPC). Она работает через сервера Яндекса, **и показывает треки даже с других устройств**."
но треки он не показыват, трек играет на яндекс станция лайт 2, и в консоле ничег нету что могло бы говорить о получении информации о треке на других утсройствах

**Comment by FozerG** [comment]
Под другими устройствами подразумевались, например, смартфоны или ноутбуки. Яндекс.Станция использует собственный протокол в локальной сети, поэтому получить информацию о текущем треке со станции невозможно

**Comment by FozerG** [comment]
Кроме того, ты пишешь не в тот репозиторий.
