### ISSUE TITLE
Не работает с треками загруженными самостоятельно на Яндекс.Музыку

### ISSUE THREAD

**Issue by donelofficial** [FozerG/WinYandexMusicRPC#9]
При попытке запустить трек, которого нет на яндекс.музыке, но был загружен мною, в консоль выводится ошибка "Can't find the song" и после этого в дискорде ничего не появляется. Насколько я понял данный скрипт не привязан к api Яндекс.Музыки, поэтому не понимаю почему это не работает.
Если проблема в функции поиска трека, то можно было бы сделать проверку на наличие трека в яндекс.музыке и если его нет, то просто выводить название, исполнителя и обложку через winsdk.windows.media.control без кнопки перехода к треку в яндекс.музыке.
Ну или для таких треков реализовать отдельный поиск (по last.fm например) и выводить кнопку перехода на трек в стороннем сервисе (но это уже лишние действия).

**Comment by FozerG** [comment]
Да, это связано с тем как работает скрипт. Скрипт в данный момент выводит только музыку которая есть в поиске на Яндекс.Музыке. Можно бы выводить музыку которой нет в поиске, как ты предлагаешь, но проблема возникает в том что нельзя отличить музыку от другой мультимедии. Допустим, открытие видео на ютубе - так же будет отображаться в статусе. Так что в данный момент такая функция не в планах.
